In [1]:
import numpy as np
import torch

from clonal_genealogy import ClonalTree
from ClonalOrigin_simulator import ClonalOrigin_simulator
from ClonalOrigin_sim_n import ClonalOrigin_sim_n

In [2]:
torch_device = "cpu"


np.random.seed(100)
tree = ClonalTree(n=15)

rho_site = 0.02
theta_site = 0.05
L = 1000000
delta = 300

x_o = ClonalOrigin_simulator(tree, rho_site, theta_site, L, delta, N=2000, k_vec=[50, 200, 2000])
x_o = torch.tensor(x_o, device=torch_device)
x_o = x_o.flatten()
x_o_numpy = x_o.cpu().numpy()
x_o_numpy

array([0.20859493, 0.12730937, 0.09281016, 0.0675    , 0.1225    ,
       0.1625    , 0.03138889, 0.31841391])

In [3]:
def prior_simulator():
    theta = [None] * 2
    theta[0] = np.random.uniform(0.0, 0.2)
    theta[1] = np.random.uniform(0.0, 0.2)
    N = np.random.randint(100, 2001, size=10)
    return theta, N

In [4]:
simulation_budget = 10

In [5]:
theta_mat = np.zeros((simulation_budget*10, 3))
x_mat = np.zeros((simulation_budget*10, 9))

In [6]:
for i in range(simulation_budget):
    theta, N_vec = prior_simulator()
    s_mat = ClonalOrigin_sim_n(tree, theta[0], theta[1], L, delta, N=N_vec, k_vec=[50, 200, 2000])

    theta_mat[i*10:(i+1)*10, :2] = theta
    theta_mat[i*10:(i+1)*10, 2] = N_vec
    x_mat[i*10:(i+1)*10, :] = s_mat

    print(f"Simulation {i+1} completed.")

Simulation 1 completed.
Simulation 2 completed.
Simulation 3 completed.
Simulation 4 completed.
Simulation 5 completed.
Simulation 6 completed.
Simulation 7 completed.
Simulation 8 completed.
Simulation 9 completed.
Simulation 10 completed.


In [10]:
theta_mat[:21, :]

array([[8.27397914e-02, 1.25889563e-01, 1.52000000e+02],
       [8.27397914e-02, 1.25889563e-01, 1.41000000e+02],
       [8.27397914e-02, 1.25889563e-01, 1.22400000e+03],
       [8.27397914e-02, 1.25889563e-01, 1.93500000e+03],
       [8.27397914e-02, 1.25889563e-01, 1.63100000e+03],
       [8.27397914e-02, 1.25889563e-01, 1.44000000e+03],
       [8.27397914e-02, 1.25889563e-01, 1.29200000e+03],
       [8.27397914e-02, 1.25889563e-01, 2.86000000e+02],
       [8.27397914e-02, 1.25889563e-01, 7.66000000e+02],
       [8.27397914e-02, 1.25889563e-01, 1.56500000e+03],
       [1.23355044e-01, 1.36485644e-01, 7.11000000e+02],
       [1.23355044e-01, 1.36485644e-01, 7.68000000e+02],
       [1.23355044e-01, 1.36485644e-01, 1.95000000e+02],
       [1.23355044e-01, 1.36485644e-01, 1.85700000e+03],
       [1.23355044e-01, 1.36485644e-01, 3.89000000e+02],
       [1.23355044e-01, 1.36485644e-01, 8.59000000e+02],
       [1.23355044e-01, 1.36485644e-01, 1.26900000e+03],
       [1.23355044e-01, 1.36485

In [11]:
x_mat[:21, 8]

array([ 152.,  141., 1224., 1935., 1631., 1440., 1292.,  286.,  766.,
       1565.,  711.,  768.,  195., 1857.,  389.,  859., 1269., 1059.,
       1244., 1360.,  674.])