In [1]:
import numpy as np
import scipy.stats as stats
from ClonalOrigin_pair import ARG
from add_mutation_truncated import add_mutation_truncated
from G3_test import G3_test
from LD_r import LD_r
from homoplasy_index import homoplasy_index

In [5]:
N = np.random.randint(100, 10001, size=10)
s_mat = np.full((len(N), 9), np.nan)
s_mat[:, 8] = N
s_mat

array([[  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan, 3990.],
       [  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan, 4563.],
       [  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan, 3862.],
       [  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan, 7917.],
       [  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan, 8195.],
       [  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan, 1592.],
       [  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan, 9252.],
       [  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan, 4220.],
       [  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan, 1372.],
       [  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan, 2025.]])

In [7]:
N

array([3990, 4563, 3862, 7917, 8195, 1592, 9252, 4220, 1372, 2025],
      dtype=int32)

In [14]:
desc_indices = np.argsort(N)[::-1]
N_max = N[desc_indices[0]]
desc_indices, N_max

(array([6, 4, 3, 1, 7, 0, 2, 9, 5, 8]), np.int32(9252))

In [12]:
int(np.max(N))

9252

In [10]:
max(N)

np.int32(9252)

In [15]:
for idx in desc_indices:
    print(idx)

6
4
3
1
7
0
2
9
5
8


In [16]:
np.arange(9252)

array([   0,    1,    2, ..., 9249, 9250, 9251], shape=(9252,))

In [17]:
np.random.randint(0, 9252, size=3990)

array([ 892,  772, 1134, ..., 5758, 8450, 9112],
      shape=(3990,), dtype=int32)

In [ ]:
for i in range(len(N)):
        idx = desc_indices[i]
        N_val = N[idx]
        if i > 0:
            choose_idx = np.random.randint(0, N_max, size=N_val)
        else:
            choose_idx = np.arange(N_val)

        print([idx, N_val])

[np.int64(6), np.int32(9252)]
[np.int64(4), np.int32(8195)]
[np.int64(3), np.int32(7917)]
[np.int64(1), np.int32(4563)]
[np.int64(7), np.int32(4220)]
[np.int64(0), np.int32(3990)]
[np.int64(2), np.int32(3862)]
[np.int64(9), np.int32(2025)]
[np.int64(5), np.int32(1592)]
[np.int64(8), np.int32(1372)]


In [20]:
v_h = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15]])
v_h

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [26]:
np.mean(v_h[:, [0, 1, 2]])

np.float64(7.0)

In [23]:
v_h[:, [0, 1, 2]]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])