# Generate and read fully simulated data from ClonalOrigin model

In [1]:
import numpy as np
from pathlib import Path
from tqdm import tqdm
import sys
sys.path.append('../pysimARG')
from clonal_genealogy import ClonalTree
from ClonalOrigin_seq_sim import ClonalOrigin_seq_sim

## Clonal tree

In [2]:
np.random.seed(100)
clonal_tree = ClonalTree(n=30)
edge = clonal_tree.edge
node_height = clonal_tree.node_height

In [3]:
edge, node_height

(array([[3.10000000e+01, 1.40000000e+01, 1.80220314e-03],
        [3.10000000e+01, 2.90000000e+01, 1.80220314e-03],
        [3.20000000e+01, 2.80000000e+01, 5.97471972e-03],
        [3.20000000e+01, 2.60000000e+01, 5.97471972e-03],
        [3.30000000e+01, 3.00000000e+00, 8.25024952e-03],
        [3.30000000e+01, 2.70000000e+01, 8.25024952e-03],
        [3.40000000e+01, 2.20000000e+01, 1.30036692e-02],
        [3.40000000e+01, 1.00000000e+01, 1.30036692e-02],
        [3.50000000e+01, 1.10000000e+01, 2.34636374e-02],
        [3.50000000e+01, 1.80000000e+01, 2.34636374e-02],
        [3.60000000e+01, 3.30000000e+01, 1.80941931e-02],
        [3.60000000e+01, 2.10000000e+01, 2.63444427e-02],
        [3.70000000e+01, 1.70000000e+01, 3.56575696e-02],
        [3.70000000e+01, 6.00000000e+00, 3.56575696e-02],
        [3.80000000e+01, 1.20000000e+01, 3.73864931e-02],
        [3.80000000e+01, 3.20000000e+01, 3.14117734e-02],
        [3.90000000e+01, 3.00000000e+01, 3.85383268e-02],
        [3.900

In [4]:
print(edge)
print(node_height)

[[3.10000000e+01 1.40000000e+01 1.80220314e-03]
 [3.10000000e+01 2.90000000e+01 1.80220314e-03]
 [3.20000000e+01 2.80000000e+01 5.97471972e-03]
 [3.20000000e+01 2.60000000e+01 5.97471972e-03]
 [3.30000000e+01 3.00000000e+00 8.25024952e-03]
 [3.30000000e+01 2.70000000e+01 8.25024952e-03]
 [3.40000000e+01 2.20000000e+01 1.30036692e-02]
 [3.40000000e+01 1.00000000e+01 1.30036692e-02]
 [3.50000000e+01 1.10000000e+01 2.34636374e-02]
 [3.50000000e+01 1.80000000e+01 2.34636374e-02]
 [3.60000000e+01 3.30000000e+01 1.80941931e-02]
 [3.60000000e+01 2.10000000e+01 2.63444427e-02]
 [3.70000000e+01 1.70000000e+01 3.56575696e-02]
 [3.70000000e+01 6.00000000e+00 3.56575696e-02]
 [3.80000000e+01 1.20000000e+01 3.73864931e-02]
 [3.80000000e+01 3.20000000e+01 3.14117734e-02]
 [3.90000000e+01 3.00000000e+01 3.85383268e-02]
 [3.90000000e+01 2.00000000e+01 3.85383268e-02]
 [4.00000000e+01 1.50000000e+01 4.75114602e-02]
 [4.00000000e+01 8.00000000e+00 4.75114602e-02]
 [4.10000000e+01 3.60000000e+01 2.503177

In [5]:
print(clonal_tree.height)
print(clonal_tree.length)

1.3283859639923548
5.896919901171329


In [5]:
# np.savetxt("../data/ClonalOrigin/clonal_edge.csv", edge, delimiter=",")
# np.savetxt("../data/ClonalOrigin/clonal_node_height.csv", node_height, delimiter=",")
# clonal_edge = np.loadtxt("../data/ClonalOrigin/clonal_edge.csv", delimiter=",", dtype=float)
# clonal_node_height = np.loadtxt("../data/ClonalOrigin/clonal_node_height.csv", delimiter=",", dtype=float)

## Simulated observations

In [12]:
rho_fix = 0.02
theta_fix = 0.05
delta_fix = 300
L = [500, 2000, 6000]

np.random.seed(1000)

In [13]:
x_o_500  = np.full((100, 46), np.nan)
x_o_2000 = np.full((100, 46), np.nan)
x_o_6000 = np.full((100, 46), np.nan)
x_o_500.shape, x_o_2000.shape, x_o_6000.shape

((100, 46), (100, 46), (100, 46))

In [14]:
for i in tqdm(range(100), desc="Simulating ClonalOrigin sequences of length 500"):
    s_vec = ClonalOrigin_seq_sim(clonal_tree, rho_fix, theta_fix, L[0], delta_fix)
    x_o_500[i, :] = s_vec

Simulating ClonalOrigin sequences of length 500: 100%|██████████| 100/100 [00:20<00:00,  4.94it/s]


In [15]:
for i in tqdm(range(100), desc="Simulating ClonalOrigin sequences of length 2000"):
    s_vec = ClonalOrigin_seq_sim(clonal_tree, rho_fix, theta_fix, L[1], delta_fix)
    x_o_2000[i, :] = s_vec

Simulating ClonalOrigin sequences of length 2000: 100%|██████████| 100/100 [03:49<00:00,  2.29s/it]


In [16]:
for i in tqdm(range(100), desc="Simulating ClonalOrigin sequences of length 6000"):
    s_vec = ClonalOrigin_seq_sim(clonal_tree, rho_fix, theta_fix, L[2], delta_fix)
    x_o_6000[i, :] = s_vec

Simulating ClonalOrigin sequences of length 6000: 100%|██████████| 100/100 [39:53<00:00, 23.94s/it]


In [17]:
x_o_500, x_o_2000, x_o_6000

(array([[2.21740000e+02, 6.33622222e+01, 5.37030745e+03, ...,
         5.47104464e-01, 1.32051751e-01, 5.00000000e+02],
        [1.12543333e+02, 3.95333333e+01, 2.22242144e+03, ...,
         1.87202462e-02, 1.26583209e-01, 5.00000000e+02],
        [2.98866667e+01, 7.50777778e+00, 1.12464132e+03, ...,
         8.03581397e-03, 7.39455546e-02, 5.00000000e+02],
        ...,
        [1.31807778e+02, 2.25066667e+01, 2.57854920e+03, ...,
         2.45518940e-01, 1.69622413e-01, 5.00000000e+02],
        [1.64432222e+02, 3.25900000e+01, 3.90255486e+03, ...,
         9.77754190e-03, 7.46299764e-02, 5.00000000e+02],
        [1.66343333e+02, 3.55855556e+01, 4.02623162e+03, ...,
         1.07684657e-02, 5.63080106e-02, 5.00000000e+02]], shape=(100, 46)),
 array([[9.16068889e+02, 2.87933333e+02, 4.08276041e+04, ...,
         1.06164353e-02, 7.36488544e-02, 2.00000000e+03],
        [2.08138333e+03, 5.57764444e+02, 5.14782417e+04, ...,
         1.18325446e-02, 8.77556234e-02, 2.00000000e+03],
        

In [18]:
np.savetxt("../data/ClonalOrigin/x_o_500.csv", x_o_500, delimiter=",")
np.savetxt("../data/ClonalOrigin/x_o_2000.csv", x_o_2000, delimiter=",")
np.savetxt("../data/ClonalOrigin/x_o_6000.csv", x_o_6000, delimiter=",")