# Generate and read fully simulated data from ClonalOrigin model

In [1]:
import numpy as np
from pathlib import Path
from tqdm import tqdm
import sys
sys.path.append('../pysimARG')
from clonal_genealogy import ClonalTree
from ClonalOrigin_seq_sim import ClonalOrigin_seq_sim

## Clonal tree

In [2]:
np.random.seed(100)
clonal_tree = ClonalTree(n=30)
edge = clonal_tree.edge
node_height = clonal_tree.node_height

In [3]:
edge, node_height

(array([[3.10000000e+01, 1.40000000e+01, 1.80220314e-03],
        [3.10000000e+01, 2.90000000e+01, 1.80220314e-03],
        [3.20000000e+01, 2.80000000e+01, 5.97471972e-03],
        [3.20000000e+01, 2.60000000e+01, 5.97471972e-03],
        [3.30000000e+01, 3.00000000e+00, 8.25024952e-03],
        [3.30000000e+01, 2.70000000e+01, 8.25024952e-03],
        [3.40000000e+01, 2.20000000e+01, 1.30036692e-02],
        [3.40000000e+01, 1.00000000e+01, 1.30036692e-02],
        [3.50000000e+01, 1.10000000e+01, 2.34636374e-02],
        [3.50000000e+01, 1.80000000e+01, 2.34636374e-02],
        [3.60000000e+01, 3.30000000e+01, 1.80941931e-02],
        [3.60000000e+01, 2.10000000e+01, 2.63444427e-02],
        [3.70000000e+01, 1.70000000e+01, 3.56575696e-02],
        [3.70000000e+01, 6.00000000e+00, 3.56575696e-02],
        [3.80000000e+01, 1.20000000e+01, 3.73864931e-02],
        [3.80000000e+01, 3.20000000e+01, 3.14117734e-02],
        [3.90000000e+01, 3.00000000e+01, 3.85383268e-02],
        [3.900

In [6]:
print(edge)
print(node_height)

[[3.10000000e+01 1.40000000e+01 1.80220314e-03]
 [3.10000000e+01 2.90000000e+01 1.80220314e-03]
 [3.20000000e+01 2.80000000e+01 5.97471972e-03]
 [3.20000000e+01 2.60000000e+01 5.97471972e-03]
 [3.30000000e+01 3.00000000e+00 8.25024952e-03]
 [3.30000000e+01 2.70000000e+01 8.25024952e-03]
 [3.40000000e+01 2.20000000e+01 1.30036692e-02]
 [3.40000000e+01 1.00000000e+01 1.30036692e-02]
 [3.50000000e+01 1.10000000e+01 2.34636374e-02]
 [3.50000000e+01 1.80000000e+01 2.34636374e-02]
 [3.60000000e+01 3.30000000e+01 1.80941931e-02]
 [3.60000000e+01 2.10000000e+01 2.63444427e-02]
 [3.70000000e+01 1.70000000e+01 3.56575696e-02]
 [3.70000000e+01 6.00000000e+00 3.56575696e-02]
 [3.80000000e+01 1.20000000e+01 3.73864931e-02]
 [3.80000000e+01 3.20000000e+01 3.14117734e-02]
 [3.90000000e+01 3.00000000e+01 3.85383268e-02]
 [3.90000000e+01 2.00000000e+01 3.85383268e-02]
 [4.00000000e+01 1.50000000e+01 4.75114602e-02]
 [4.00000000e+01 8.00000000e+00 4.75114602e-02]
 [4.10000000e+01 3.60000000e+01 2.503177

In [7]:
print(clonal_tree.height)
print(clonal_tree.length)

1.3283859639923548
5.896919901171329


In [5]:
# np.savetxt("../data/ClonalOrigin/clonal_edge.csv", edge, delimiter=",")
# np.savetxt("../data/ClonalOrigin/clonal_node_height.csv", node_height, delimiter=",")
# clonal_edge = np.loadtxt("../data/ClonalOrigin/clonal_edge.csv", delimiter=",", dtype=float)
# clonal_node_height = np.loadtxt("../data/ClonalOrigin/clonal_node_height.csv", delimiter=",", dtype=float)