In [1]:
import numpy as np
from Bio import Phylo
import sys
sys.path.append('../pysimARG')
from clonal_genealogy import ClonalTree
from newick_to_tree import newick_to_tree
from ClonalOrigin_seq_sim import ClonalOrigin_seq_sim
from segment_summary_stats import segment_summary_stats
import warnings
warnings.filterwarnings('ignore', category=RuntimeWarning)

In [2]:
genome_simbac = np.loadtxt("../data/SimBac/genomes_bool.csv", delimiter=",", dtype=bool)

In [3]:
genome_simbac.shape

(30, 1000000)

In [4]:
np.random.seed(100)
clonal_tree = ClonalTree(n=30)

# Load phylo tree and convert to ClonalTree format
phylo_tree = Phylo.read("../data/SimBac/clonal_frame.nwk", "newick")
Phylo.draw_ascii(phylo_tree)

edge, node_height = newick_to_tree(phylo_tree)
clonal_tree.edge = edge
clonal_tree.node_height = node_height
clonal_tree.height = np.max(node_height)
clonal_tree.length = np.sum(edge[:, 2])

                                                                    ____ 14
                                                                   |
                                                                   |    , 15
                                                        ___________|   _|
                                                       |           |  | , 5
                                                       |           |  | |
                                                       |           |__| | 24
                                                       |              |
                                                       |              | , 27
                                                       |              |_|
                                                       |                | 4
                                                       |
                                                       |      __________ 18
                                             

In [5]:
x_o_500 = np.full((100, 46), np.nan)
x_o_2000 = np.full((100, 46), np.nan)
x_o_6000 = np.full((100, 46), np.nan)

x_o_500, x_o_2000, x_o_6000

(array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]], shape=(100, 46)),
 array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]], shape=(100, 46)),
 array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]], shape=(100, 46)))

In [6]:
np.random.seed(500)
L = 500

for idx in range(100):
    start_pos = np.random.randint(1, genome_simbac.shape[1]-L+1)
    mat = genome_simbac[:, start_pos-1:start_pos+L-1]

    s_vec = segment_summary_stats(clonal_tree, mat)
    x_o_500[idx, :] = s_vec

    if (idx + 1) % 10 == 0:
        print(f"Completed {idx + 1} out of 100 simulations for L=500")

x_o_500

Completed 10 out of 100 simulations for L=500
Completed 20 out of 100 simulations for L=500
Completed 30 out of 100 simulations for L=500
Completed 40 out of 100 simulations for L=500
Completed 50 out of 100 simulations for L=500
Completed 60 out of 100 simulations for L=500
Completed 70 out of 100 simulations for L=500
Completed 80 out of 100 simulations for L=500
Completed 90 out of 100 simulations for L=500
Completed 100 out of 100 simulations for L=500


array([[8.38255556e+01, 2.07344444e+01, 2.51493461e+03, ...,
        2.52990409e-02, 8.78279899e-02, 5.00000000e+02],
       [1.24284444e+02, 2.99533333e+01, 3.82736383e+03, ...,
        2.07069069e-03, 1.00027375e-02, 5.00000000e+02],
       [1.04983333e+02, 2.05088889e+01, 3.19826773e+03, ...,
        3.16346655e-02, 7.83423407e-02, 5.00000000e+02],
       ...,
       [6.39800000e+01, 8.81444444e+00, 2.34358987e+03, ...,
        5.70002215e-03, 2.06960506e-02, 5.00000000e+02],
       [2.59400000e+01, 9.30666667e+00, 1.34185109e+03, ...,
        2.49293284e+01, 7.86145239e-02, 5.00000000e+02],
       [2.32177778e+01, 7.24000000e+00, 1.11394353e+03, ...,
        4.64456673e-02, 9.08429762e-02, 5.00000000e+02]], shape=(100, 46))

In [7]:
np.random.seed(2000)
L = 2000

for idx in range(100):
    start_pos = np.random.randint(1, genome_simbac.shape[1]-L+1)
    mat = genome_simbac[:, start_pos-1:start_pos+L-1]

    s_vec = segment_summary_stats(clonal_tree, mat)
    x_o_2000[idx, :] = s_vec

    if (idx + 1) % 10 == 0:
        print(f"Completed {idx + 1} out of 100 simulations for L=2000")

x_o_2000

Completed 10 out of 100 simulations for L=2000
Completed 20 out of 100 simulations for L=2000
Completed 30 out of 100 simulations for L=2000
Completed 40 out of 100 simulations for L=2000
Completed 50 out of 100 simulations for L=2000


c:\Users\u2008181\likelihood-free\python\../pysimARG\exp_regression.py:34: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, pcov = curve_fit(shifted_exponential, x_scaled, y, p0=initial_guess)


Completed 60 out of 100 simulations for L=2000
Completed 70 out of 100 simulations for L=2000
Completed 80 out of 100 simulations for L=2000
Completed 90 out of 100 simulations for L=2000
Completed 100 out of 100 simulations for L=2000


array([[1.07361556e+03, 2.91360000e+02, 3.40127764e+04, ...,
        1.14668518e-02, 8.17260193e-02, 2.00000000e+03],
       [1.27543000e+03, 2.93531111e+02, 4.73701432e+04, ...,
        1.14641846e-02, 5.29508220e-02, 2.00000000e+03],
       [1.18963222e+03, 3.04562222e+02, 3.44958793e+04, ...,
        6.54358630e-03, 7.07834174e-02, 2.00000000e+03],
       ...,
       [7.09706667e+02, 1.67538889e+02, 2.98963955e+04, ...,
        8.37043591e-03, 6.21676496e-02, 2.00000000e+03],
       [6.19395556e+02, 1.68933333e+02, 3.23361141e+04, ...,
        9.50818045e-03, 6.01108263e-02, 2.00000000e+03],
       [1.13145111e+03, 3.31790000e+02, 3.08209684e+04, ...,
        8.56699708e-03, 9.31573906e-02, 2.00000000e+03]], shape=(100, 46))

In [8]:
np.random.seed(6000)
L = 6000

for idx in range(100):
    start_pos = np.random.randint(1, genome_simbac.shape[1]-L+1)
    mat = genome_simbac[:, start_pos-1:start_pos+L-1]

    s_vec = segment_summary_stats(clonal_tree, mat)
    x_o_6000[idx, :] = s_vec

    if (idx + 1) % 10 == 0:
        print(f"Completed {idx + 1} out of 100 simulations for L=6000")

x_o_6000

c:\Users\u2008181\likelihood-free\python\../pysimARG\exp_regression.py:34: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, pcov = curve_fit(shifted_exponential, x_scaled, y, p0=initial_guess)


Completed 10 out of 100 simulations for L=6000
Completed 20 out of 100 simulations for L=6000
Completed 30 out of 100 simulations for L=6000
Completed 40 out of 100 simulations for L=6000
Completed 50 out of 100 simulations for L=6000
Completed 60 out of 100 simulations for L=6000
Completed 70 out of 100 simulations for L=6000
Completed 80 out of 100 simulations for L=6000
Completed 90 out of 100 simulations for L=6000


c:\Users\u2008181\likelihood-free\python\../pysimARG\exp_regression.py:34: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, pcov = curve_fit(shifted_exponential, x_scaled, y, p0=initial_guess)


Completed 100 out of 100 simulations for L=6000


array([[7.38590444e+03, 2.36140222e+03, 2.58908638e+05, ...,
        1.34451886e-02, 8.82951338e-02, 6.00000000e+03],
       [9.54418000e+03, 3.09624889e+03, 3.53617681e+05, ...,
        5.46098725e-03, 7.05022829e-02, 6.00000000e+03],
       [8.88170889e+03, 2.89998111e+03, 3.17874908e+05, ...,
        9.73224538e-03, 6.90268596e-02, 6.00000000e+03],
       ...,
       [8.49077778e+03, 2.97992000e+03, 3.03559047e+05, ...,
        9.87706218e-03, 6.97222795e-02, 6.00000000e+03],
       [1.04149722e+04, 2.74996111e+03, 3.52261129e+05, ...,
        7.98795617e-03, 6.48684112e-02, 6.00000000e+03],
       [8.33838444e+03, 2.57259667e+03, 2.80267222e+05, ...,
        6.22849706e-03, 7.69996650e-02, 6.00000000e+03]], shape=(100, 46))

In [9]:
x_o_500_CO  = np.full((100, 46), np.nan)
x_o_2000_CO = np.full((100, 46), np.nan)
x_o_6000_CO = np.full((100, 46), np.nan)

rho_site = 0.02
theta_site = 0.05
delta = 300

x_o_500_CO, x_o_2000_CO, x_o_6000_CO

(array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]], shape=(100, 46)),
 array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]], shape=(100, 46)),
 array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]], shape=(100, 46)))

In [10]:
np.random.seed(500)
for idx in range(100):
    s_vec = ClonalOrigin_seq_sim(clonal_tree, rho_site, theta_site, 500, delta)
    x_o_500_CO[idx, :] = s_vec

    if (idx + 1) % 10 == 0:
        print(f"Completed {idx + 1} out of 100 simulations for L=500 using ClonalOrigin.")

x_o_500_CO

Completed 10 out of 100 simulations for L=500 using ClonalOrigin.
Completed 20 out of 100 simulations for L=500 using ClonalOrigin.
Completed 30 out of 100 simulations for L=500 using ClonalOrigin.
Completed 40 out of 100 simulations for L=500 using ClonalOrigin.


c:\Users\u2008181\likelihood-free\python\../pysimARG\exp_regression.py:34: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, pcov = curve_fit(shifted_exponential, x_scaled, y, p0=initial_guess)
c:\Users\u2008181\likelihood-free\python\../pysimARG\exp_regression.py:34: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, pcov = curve_fit(shifted_exponential, x_scaled, y, p0=initial_guess)


Completed 50 out of 100 simulations for L=500 using ClonalOrigin.
Completed 60 out of 100 simulations for L=500 using ClonalOrigin.
Completed 70 out of 100 simulations for L=500 using ClonalOrigin.


c:\Users\u2008181\likelihood-free\python\../pysimARG\exp_regression.py:34: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, pcov = curve_fit(shifted_exponential, x_scaled, y, p0=initial_guess)


Completed 80 out of 100 simulations for L=500 using ClonalOrigin.
Completed 90 out of 100 simulations for L=500 using ClonalOrigin.
Completed 100 out of 100 simulations for L=500 using ClonalOrigin.


array([[2.90211111e+01, 8.90777778e+00, 1.81232274e+03, ...,
        8.45857479e-03, 4.78766162e-02, 5.00000000e+02],
       [1.76925556e+02, 4.93388889e+01, 2.23790519e+03, ...,
        4.28952957e-03, 1.11545925e-01, 5.00000000e+02],
       [8.30766667e+01, 3.52666667e+01, 2.80333190e+03, ...,
        2.86069468e-02, 7.96582696e-02, 5.00000000e+02],
       ...,
       [1.83154444e+02, 3.26455556e+01, 4.15038888e+03, ...,
        5.50414264e-03, 3.52554805e-02, 5.00000000e+02],
       [2.08298889e+02, 6.99944444e+01, 3.78517639e+03, ...,
        1.78897711e-02, 8.65408033e-02, 5.00000000e+02],
       [7.33255556e+01, 1.89688889e+01, 1.98305601e+03, ...,
        1.52190227e-02, 1.08745791e-01, 5.00000000e+02]], shape=(100, 46))

In [11]:
np.random.seed(2000)
for idx in range(100):
    s_vec = ClonalOrigin_seq_sim(clonal_tree, rho_site, theta_site, 2000, delta)
    x_o_2000_CO[idx, :] = s_vec

    if (idx + 1) % 10 == 0:
        print(f"Completed {idx + 1} out of 100 simulations for L=2000 using ClonalOrigin.")

x_o_2000_CO

Completed 10 out of 100 simulations for L=2000 using ClonalOrigin.
Completed 20 out of 100 simulations for L=2000 using ClonalOrigin.
Completed 30 out of 100 simulations for L=2000 using ClonalOrigin.
Completed 40 out of 100 simulations for L=2000 using ClonalOrigin.
Completed 50 out of 100 simulations for L=2000 using ClonalOrigin.
Completed 60 out of 100 simulations for L=2000 using ClonalOrigin.


c:\Users\u2008181\likelihood-free\python\../pysimARG\exp_regression.py:34: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, pcov = curve_fit(shifted_exponential, x_scaled, y, p0=initial_guess)


Completed 70 out of 100 simulations for L=2000 using ClonalOrigin.
Completed 80 out of 100 simulations for L=2000 using ClonalOrigin.
Completed 90 out of 100 simulations for L=2000 using ClonalOrigin.
Completed 100 out of 100 simulations for L=2000 using ClonalOrigin.


array([[1.13175889e+03, 3.91807778e+02, 4.78233725e+04, ...,
        4.72384110e-03, 6.51858550e-02, 2.00000000e+03],
       [5.12514889e+03, 1.05128000e+03, 8.68081562e+04, ...,
        6.78921001e-03, 1.00856826e-01, 2.00000000e+03],
       [9.41493333e+02, 3.42376667e+02, 3.72194988e+04, ...,
        3.19144626e-03, 5.30498278e-02, 2.00000000e+03],
       ...,
       [3.77826556e+03, 5.79497778e+02, 6.25025334e+04, ...,
        4.12247023e-03, 8.78709865e-02, 2.00000000e+03],
       [1.52544333e+03, 4.24623333e+02, 6.24594389e+04, ...,
        5.21760505e-03, 7.10439944e-02, 2.00000000e+03],
       [1.52283889e+03, 3.93986667e+02, 4.56439990e+04, ...,
        6.99811376e-03, 7.29739856e-02, 2.00000000e+03]], shape=(100, 46))

In [12]:
np.random.seed(6000)
for idx in range(100):
    s_vec = ClonalOrigin_seq_sim(clonal_tree, rho_site, theta_site, 6000, delta)
    x_o_6000_CO[idx, :] = s_vec

    if (idx + 1) % 10 == 0:
        print(f"Completed {idx + 1} out of 100 simulations for L=6000 using ClonalOrigin.")

x_o_6000_CO

Completed 10 out of 100 simulations for L=6000 using ClonalOrigin.
Completed 20 out of 100 simulations for L=6000 using ClonalOrigin.
Completed 30 out of 100 simulations for L=6000 using ClonalOrigin.
Completed 40 out of 100 simulations for L=6000 using ClonalOrigin.
Completed 50 out of 100 simulations for L=6000 using ClonalOrigin.
Completed 60 out of 100 simulations for L=6000 using ClonalOrigin.
Completed 70 out of 100 simulations for L=6000 using ClonalOrigin.


c:\Users\u2008181\likelihood-free\python\../pysimARG\exp_regression.py:34: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, pcov = curve_fit(shifted_exponential, x_scaled, y, p0=initial_guess)


Completed 80 out of 100 simulations for L=6000 using ClonalOrigin.
Completed 90 out of 100 simulations for L=6000 using ClonalOrigin.
Completed 100 out of 100 simulations for L=6000 using ClonalOrigin.


array([[1.38465678e+04, 3.10605333e+03, 4.81104851e+05, ...,
        6.26714605e-03, 6.28397406e-02, 6.00000000e+03],
       [1.28804067e+04, 4.11095111e+03, 4.44471080e+05, ...,
        9.90840769e-03, 8.05869703e-02, 6.00000000e+03],
       [1.21858278e+04, 3.83570333e+03, 4.10960512e+05, ...,
        5.80504213e-03, 6.38307859e-02, 6.00000000e+03],
       ...,
       [2.26519322e+04, 6.06748778e+03, 5.73849251e+05, ...,
        5.27987944e-03, 7.47216276e-02, 6.00000000e+03],
       [1.52488200e+04, 5.43223222e+03, 5.91900054e+05, ...,
        3.86038783e-03, 6.99327272e-02, 6.00000000e+03],
       [2.15645744e+04, 4.84402778e+03, 5.97030241e+05, ...,
        8.06703490e-03, 7.94397464e-02, 6.00000000e+03]], shape=(100, 46))

In [13]:
np.savetxt('../data/x_500_SB.csv', x_o_500, delimiter=",")
np.savetxt('../data/x_2000_SB.csv', x_o_2000, delimiter=",")
np.savetxt('../data/x_6000_SB.csv', x_o_6000, delimiter=",")
np.savetxt('../data/x_500_CO.csv', x_o_500_CO, delimiter=",")
np.savetxt('../data/x_2000_CO.csv', x_o_2000_CO, delimiter=",")
np.savetxt('../data/x_6000_CO.csv', x_o_6000_CO, delimiter=",")