In [1]:
import numpy as np
from Bio import Phylo
import sys
sys.path.append('../pysimARG')
from clonal_genealogy import ClonalTree
from newick_to_tree import newick_to_tree
from ClonalOrigin_seq_sim import ClonalOrigin_seq_sim
from segment_summary_stats import segment_summary_stats
import warnings
warnings.filterwarnings('ignore', category=RuntimeWarning)

In [2]:
genome_simbac = np.loadtxt("../data/SimBac/genomes_bool.csv", delimiter=",", dtype=bool)

In [3]:
genome_simbac.shape

(30, 1000000)

In [4]:
np.random.seed(100)
clonal_tree = ClonalTree(n=30)

# Load phylo tree and convert to ClonalTree format
phylo_tree = Phylo.read("../data/SimBac/clonal_frame.nwk", "newick")
Phylo.draw_ascii(phylo_tree)

edge, node_height = newick_to_tree(phylo_tree)
clonal_tree.edge = edge
clonal_tree.node_height = node_height
clonal_tree.height = np.max(node_height)
clonal_tree.length = np.sum(edge[:, 2])

                                                                    ____ 14
                                                                   |
                                                                   |    , 15
                                                        ___________|   _|
                                                       |           |  | , 5
                                                       |           |  | |
                                                       |           |__| | 24
                                                       |              |
                                                       |              | , 27
                                                       |              |_|
                                                       |                | 4
                                                       |
                                                       |      __________ 18
                                             

In [5]:
x_o_500 = np.full((100, 46), np.nan)
x_o_2000 = np.full((100, 46), np.nan)
x_o_6000 = np.full((100, 46), np.nan)

x_o_500, x_o_2000, x_o_6000

(array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]], shape=(100, 46)),
 array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]], shape=(100, 46)),
 array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]], shape=(100, 46)))

In [6]:
np.random.seed(500)
L = 500

for idx in range(100):
    start_pos = np.random.randint(1, genome_simbac.shape[1]-L+1)
    mat = genome_simbac[:, start_pos-1:start_pos+L-1]

    s_vec = segment_summary_stats(clonal_tree, mat)
    x_o_500[idx, :] = s_vec

    if (idx + 1) % 10 == 0:
        print(f"Completed {idx + 1} out of 100 simulations for L=500")

x_o_500

Completed 10 out of 100 simulations for L=500
Completed 20 out of 100 simulations for L=500
Completed 30 out of 100 simulations for L=500
Completed 40 out of 100 simulations for L=500
Completed 50 out of 100 simulations for L=500
Completed 60 out of 100 simulations for L=500
Completed 70 out of 100 simulations for L=500
Completed 80 out of 100 simulations for L=500
Completed 90 out of 100 simulations for L=500
Completed 100 out of 100 simulations for L=500


array([[5.47900000e+01, 1.27922222e+01, 2.51493461e+03, ...,
        2.52990409e-02, 8.78279899e-02, 5.00000000e+02],
       [9.20422222e+01, 1.73733333e+01, 3.82736383e+03, ...,
        2.07069069e-03, 1.00027375e-02, 5.00000000e+02],
       [3.20633333e+01, 6.15333333e+00, 3.19826773e+03, ...,
        3.16346655e-02, 7.83423407e-02, 5.00000000e+02],
       ...,
       [3.11577778e+01, 1.58111111e+00, 2.34358987e+03, ...,
        5.70002215e-03, 2.06960506e-02, 5.00000000e+02],
       [1.13244444e+01, 3.58222222e+00, 1.34185109e+03, ...,
        2.49293284e+01, 7.86145239e-02, 5.00000000e+02],
       [1.13866667e+01, 4.62000000e+00, 1.11394353e+03, ...,
        4.64456673e-02, 9.08429762e-02, 5.00000000e+02]], shape=(100, 46))

In [7]:
np.random.seed(2000)
L = 2000

for idx in range(100):
    start_pos = np.random.randint(1, genome_simbac.shape[1]-L+1)
    mat = genome_simbac[:, start_pos-1:start_pos+L-1]

    s_vec = segment_summary_stats(clonal_tree, mat)
    x_o_2000[idx, :] = s_vec

    if (idx + 1) % 10 == 0:
        print(f"Completed {idx + 1} out of 100 simulations for L=2000")

x_o_2000

Completed 10 out of 100 simulations for L=2000
Completed 20 out of 100 simulations for L=2000
Completed 30 out of 100 simulations for L=2000
Completed 40 out of 100 simulations for L=2000
Completed 50 out of 100 simulations for L=2000


c:\Users\u2008181\likelihood-free\python\../pysimARG\exp_regression.py:34: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, pcov = curve_fit(shifted_exponential, x_scaled, y, p0=initial_guess)


Completed 60 out of 100 simulations for L=2000
Completed 70 out of 100 simulations for L=2000
Completed 80 out of 100 simulations for L=2000
Completed 90 out of 100 simulations for L=2000
Completed 100 out of 100 simulations for L=2000


array([[6.40646667e+02, 1.72948889e+02, 3.40127764e+04, ...,
        1.14668518e-02, 8.17260193e-02, 2.00000000e+03],
       [5.50243333e+02, 8.44622222e+01, 4.73701432e+04, ...,
        1.14641846e-02, 5.29508220e-02, 2.00000000e+03],
       [5.83714444e+02, 1.29988889e+02, 3.44958793e+04, ...,
        6.54358630e-03, 7.07834174e-02, 2.00000000e+03],
       ...,
       [2.46437778e+02, 3.00500000e+01, 2.98963955e+04, ...,
        8.37043591e-03, 6.21676496e-02, 2.00000000e+03],
       [2.53533333e+02, 1.98466667e+01, 3.23361141e+04, ...,
        9.50818045e-03, 6.01108263e-02, 2.00000000e+03],
       [4.92984444e+02, 1.81256667e+02, 3.08209684e+04, ...,
        8.56699708e-03, 9.31573906e-02, 2.00000000e+03]], shape=(100, 46))

In [8]:
np.random.seed(6000)
L = 6000

for idx in range(100):
    start_pos = np.random.randint(1, genome_simbac.shape[1]-L+1)
    mat = genome_simbac[:, start_pos-1:start_pos+L-1]

    s_vec = segment_summary_stats(clonal_tree, mat)
    x_o_6000[idx, :] = s_vec

    if (idx + 1) % 10 == 0:
        print(f"Completed {idx + 1} out of 100 simulations for L=6000")

x_o_6000

c:\Users\u2008181\likelihood-free\python\../pysimARG\exp_regression.py:34: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, pcov = curve_fit(shifted_exponential, x_scaled, y, p0=initial_guess)


Completed 10 out of 100 simulations for L=6000
Completed 20 out of 100 simulations for L=6000
Completed 30 out of 100 simulations for L=6000
Completed 40 out of 100 simulations for L=6000
Completed 50 out of 100 simulations for L=6000
Completed 60 out of 100 simulations for L=6000
Completed 70 out of 100 simulations for L=6000
Completed 80 out of 100 simulations for L=6000
Completed 90 out of 100 simulations for L=6000


c:\Users\u2008181\likelihood-free\python\../pysimARG\exp_regression.py:34: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, pcov = curve_fit(shifted_exponential, x_scaled, y, p0=initial_guess)


Completed 100 out of 100 simulations for L=6000


array([[2.87605778e+03, 4.83564444e+02, 2.58908638e+05, ...,
        1.34451886e-02, 8.82951338e-02, 6.00000000e+03],
       [3.17276444e+03, 1.20778889e+03, 3.53617681e+05, ...,
        5.46098725e-03, 7.05022829e-02, 6.00000000e+03],
       [3.57645778e+03, 9.17578889e+02, 3.17874908e+05, ...,
        9.73224538e-03, 6.90268596e-02, 6.00000000e+03],
       ...,
       [3.33035556e+03, 1.27910889e+03, 3.03559047e+05, ...,
        9.87706218e-03, 6.97222795e-02, 6.00000000e+03],
       [3.21615889e+03, 7.39585556e+02, 3.52261129e+05, ...,
        7.98795617e-03, 6.48684112e-02, 6.00000000e+03],
       [3.60398667e+03, 1.13832111e+03, 2.80267222e+05, ...,
        6.22849706e-03, 7.69996650e-02, 6.00000000e+03]], shape=(100, 46))

In [9]:
CO_summary_stats = np.full((3, 46), np.nan)

rho_site = 0.02
theta_site = 0.05
delta = 300
CO_summary_stats

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan]])

In [10]:
np.random.seed(100)
CO_summary_stats[0, :] = ClonalOrigin_seq_sim(clonal_tree, rho_site, theta_site, 500, delta)
CO_summary_stats[1, :] = ClonalOrigin_seq_sim(clonal_tree, rho_site, theta_site, 2000, delta)
CO_summary_stats[2, :] = ClonalOrigin_seq_sim(clonal_tree, rho_site, theta_site, 6000, delta)

CO_summary_stats

array([[-5.51111111e-01, -3.13333333e-01,  3.00599639e+03,
         7.69224495e+02,  3.65800113e+02,  4.84400474e+01,
         1.99000000e+02,  8.00000000e+01, -1.77949987e-04,
        -3.82580383e-04,  9.70615559e-01,  9.39224048e-01,
         1.18114341e-01,  5.91453570e-02,  6.42557314e-02,
         9.76800977e-02, -3.34777778e+00, -2.42444444e+00,
         4.64466723e+02,  4.57391884e+02,  6.18314470e+01,
         6.61066369e+01,  1.50000000e+01,  1.90000000e+01,
        -7.12293144e-03, -5.21385902e-03,  9.88227070e-01,
         9.83638460e-01,  1.31556270e-01,  1.42164810e-01,
         3.19148936e-02,  4.08602151e-02,  3.59712230e-01,
         1.78000000e-01,  2.24653654e+01,  1.67356322e+01,
         1.12010569e+02, -9.71420497e-01,  7.95454545e-02,
         1.23595506e-01,  7.00000000e+00,  1.05781451e-01,
        -5.56123618e-02,  2.59266356e+01,  8.59918482e-02,
         5.00000000e+02],
       [ 1.07000000e+01,  1.90000000e-01,  5.42965786e+04,
         1.99313622e+04,  6.14

In [11]:
np.savetxt('../data/x_500_mat.csv', x_o_500, delimiter=",")
np.savetxt('../data/x_2000_mat.csv', x_o_2000, delimiter=",")
np.savetxt('../data/x_6000_mat.csv', x_o_6000, delimiter=",")
np.savetxt('../data/x_o_ClonalOrigin.csv', CO_summary_stats, delimiter=",")