In [1]:
from Bio import SeqIO, Phylo
import numpy as np
import sys
sys.path.append('../pysimARG')
from fasta_to_bool import fasta_to_bool
from newick_to_tree import newick_to_tree
from clonal_genealogy import ClonalTree

In [2]:
tree = Phylo.read("../data/SimBac/clonal_frame.nwk", "newick")
Phylo.draw_ascii(tree)

                                                        _________________ 5
                                                    ___|
                                                   |   |                 , 0
                                                   |   |_________________|
           ________________________________________|                     | 10
          |                                        |
          |                                        |                    _ 11
          |                                        |___________________|
       ___|                                                            |_ 9
      |   |
      |   |                                                            __ 8
      |   |                                             ______________|
      |   |____________________________________________|              |__ 6
  ____|                                                |
 |    |                                                |_________

In [4]:
clonaltree = ClonalTree(n=15)

In [5]:
edge, node_height = newick_to_tree(tree)

In [6]:
edge

array([[2.90000e+01, 2.80000e+01, 4.71342e-02],
       [2.90000e+01, 2.10000e+01, 5.43257e-01],
       [2.80000e+01, 2.70000e+01, 3.60000e-02],
       [2.80000e+01, 2.60000e+01, 3.44459e-01],
       [2.70000e+01, 2.50000e+01, 3.38715e-01],
       [2.70000e+01, 2.40000e+01, 3.73646e-01],
       [2.50000e+01, 2.30000e+01, 3.70620e-02],
       [2.50000e+01, 1.80000e+01, 1.71777e-01],
       [2.30000e+01, 6.00000e+00, 1.53388e-01],
       [2.30000e+01, 1.70000e+01, 1.47923e-01],
       [1.70000e+01, 1.00000e+00, 5.46497e-03],
       [1.70000e+01, 1.10000e+01, 5.46497e-03],
       [1.80000e+01, 1.20000e+01, 1.86725e-02],
       [1.80000e+01, 1.00000e+01, 1.86725e-02],
       [2.40000e+01, 1.90000e+01, 1.22509e-01],
       [2.40000e+01, 3.00000e+00, 1.55519e-01],
       [1.90000e+01, 9.00000e+00, 3.30098e-02],
       [1.90000e+01, 7.00000e+00, 3.30098e-02],
       [2.60000e+01, 2.20000e+01, 1.23457e-01],
       [2.60000e+01, 8.00000e+00, 2.20706e-01],
       [2.20000e+01, 1.30000e+01, 9.7248

In [7]:
node_height

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.00371019, 0.00546497, 0.0186725 , 0.0330098 , 0.05097469,
       0.06904199, 0.0972488 , 0.15338797, 0.1555188 , 0.19044997,
       0.2207058 , 0.52916488, 0.5651648 , 0.612299  ])

In [8]:
clonaltree.edge, clonaltree.node_height

(array([[1.60000000e+01, 1.30000000e+01, 2.10663223e-02],
        [1.60000000e+01, 2.00000000e+00, 2.10663223e-02],
        [1.70000000e+01, 5.00000000e+00, 3.34346296e-02],
        [1.70000000e+01, 1.00000000e+00, 3.34346296e-02],
        [1.80000000e+01, 9.00000000e+00, 7.62507126e-02],
        [1.80000000e+01, 3.00000000e+00, 7.62507126e-02],
        [1.90000000e+01, 8.00000000e+00, 7.76114032e-02],
        [1.90000000e+01, 6.00000000e+00, 7.76114032e-02],
        [2.00000000e+01, 1.40000000e+01, 1.35948153e-01],
        [2.00000000e+01, 7.00000000e+00, 1.35948153e-01],
        [2.10000000e+01, 2.00000000e+01, 1.32700864e-01],
        [2.10000000e+01, 1.20000000e+01, 2.68649017e-01],
        [2.20000000e+01, 1.60000000e+01, 2.88693404e-01],
        [2.20000000e+01, 4.00000000e+00, 3.09759726e-01],
        [2.30000000e+01, 1.90000000e+01, 2.78156301e-01],
        [2.30000000e+01, 1.80000000e+01, 2.79516992e-01],
        [2.40000000e+01, 2.20000000e+01, 6.66050659e-02],
        [2.400

In [9]:
counter = 1
for leaf in tree.get_terminals():
    if leaf.name and leaf.name.isdigit():
        leaf.node_index = int(leaf.name)
    else:
        leaf.node_index = counter
    counter += 1

terminal_indices = [leaf.node_index for leaf in tree.get_terminals()]
next_index = max(terminal_indices) + 1 if terminal_indices else 1

for clade in tree.find_clades(terminal=False, order='postorder'):
    clade.node_index = next_index
    next_index += 1

print(counter)

16


In [33]:
height_to_root = np.zeros(counter - 1)
height_to_root

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
edge

array([[2.90000e+01, 2.80000e+01, 4.71342e-02],
       [2.90000e+01, 2.10000e+01, 5.43257e-01],
       [2.80000e+01, 2.70000e+01, 3.60000e-02],
       [2.80000e+01, 2.60000e+01, 3.44459e-01],
       [2.70000e+01, 2.50000e+01, 3.38715e-01],
       [2.70000e+01, 2.40000e+01, 3.73646e-01],
       [2.50000e+01, 2.30000e+01, 3.70620e-02],
       [2.50000e+01, 1.80000e+01, 1.71777e-01],
       [2.30000e+01, 6.00000e+00, 1.53388e-01],
       [2.30000e+01, 1.70000e+01, 1.47923e-01],
       [1.70000e+01, 1.00000e+00, 5.46497e-03],
       [1.70000e+01, 1.10000e+01, 5.46497e-03],
       [1.80000e+01, 1.20000e+01, 1.86725e-02],
       [1.80000e+01, 1.00000e+01, 1.86725e-02],
       [2.40000e+01, 1.90000e+01, 1.22509e-01],
       [2.40000e+01, 3.00000e+00, 1.55519e-01],
       [1.90000e+01, 9.00000e+00, 3.30098e-02],
       [1.90000e+01, 7.00000e+00, 3.30098e-02],
       [2.60000e+01, 2.20000e+01, 1.23457e-01],
       [2.60000e+01, 8.00000e+00, 2.20706e-01],
       [2.20000e+01, 1.30000e+01, 9.7248

In [40]:
for leaf in range(1, counter):
    height_to_leaf = 0
    start_node = leaf
    while start_node < (counter - 1)*2 - 1:
        mat_indices = np.where(edge[:, 1] == start_node)[0]
        parent_node = edge[mat_indices, 0][0]
        height_to_leaf += edge[mat_indices, 2][0]
        start_node = parent_node
    height_to_root[leaf - 1] = height_to_leaf

In [41]:
height_to_root

array([0.6122987, 0.6122987, 0.6122987, 0.6122987, 0.6122987, 0.6122987,
       0.6122987, 0.6122987, 0.6122987, 0.6122987, 0.6122987, 0.6122987,
       0.6122987, 0.6122987, 0.6122987])

In [37]:
min_height = np.min(height_to_root)
diff_height = height_to_root - min_height
min_height, diff_height

(np.float64(0.6122987000000001),
 array([4.7e-07, 3.0e-07, 5.0e-07, 3.0e-07, 3.0e-07, 5.0e-07, 3.0e-07,
        5.0e-07, 3.0e-07, 0.0e+00, 4.7e-07, 0.0e+00, 3.0e-07, 2.9e-07,
        2.9e-07]))

In [38]:
old_edge = edge.copy()

In [39]:
for leaf in range(1, counter):
    mat_indices = np.where(edge[:, 1] == leaf)[0]
    edge[mat_indices, 2] -= diff_height[leaf - 1]
edge

array([[2.900000e+01, 2.800000e+01, 4.713420e-02],
       [2.900000e+01, 2.100000e+01, 5.432570e-01],
       [2.800000e+01, 2.700000e+01, 3.600000e-02],
       [2.800000e+01, 2.600000e+01, 3.444590e-01],
       [2.700000e+01, 2.500000e+01, 3.387150e-01],
       [2.700000e+01, 2.400000e+01, 3.736460e-01],
       [2.500000e+01, 2.300000e+01, 3.706200e-02],
       [2.500000e+01, 1.800000e+01, 1.717770e-01],
       [2.300000e+01, 6.000000e+00, 1.533875e-01],
       [2.300000e+01, 1.700000e+01, 1.479230e-01],
       [1.700000e+01, 1.000000e+00, 5.464500e-03],
       [1.700000e+01, 1.100000e+01, 5.464500e-03],
       [1.800000e+01, 1.200000e+01, 1.867250e-02],
       [1.800000e+01, 1.000000e+01, 1.867250e-02],
       [2.400000e+01, 1.900000e+01, 1.225090e-01],
       [2.400000e+01, 3.000000e+00, 1.555185e-01],
       [1.900000e+01, 9.000000e+00, 3.300950e-02],
       [1.900000e+01, 7.000000e+00, 3.300950e-02],
       [2.600000e+01, 2.200000e+01, 1.234570e-01],
       [2.600000e+01, 8.000000e

In [75]:
old_node_height = node_height.copy()
node_height = np.full(next_index, np.nan)
node_height[:(counter-1)] = 0
old_node_height, node_height

(array([0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.0037099, 0.0054645, 0.0186725,
        0.0330095, 0.0509744, 0.0690417, 0.0972485, 0.1533875, 0.1555185,
        0.1904495, 0.2207055, 0.5291645, 0.5651645, 0.6122987]),
 array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0., nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan]))

In [76]:
for node in range(counter, (counter - 1)*2):
    mat_indices = np.where(edge[:, 0] == node)[0][1]
    leaf = edge[mat_indices, 1]
    node_height[node-1] = node_height[int(leaf)-1] + edge[mat_indices, 2]
node_height

array([0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.0037099, 0.0054645, 0.0186725,
       0.0330095, 0.0509744, 0.0690417, 0.0972485, 0.1533875, 0.1555185,
       0.1904495, 0.2207055, 0.5291645, 0.5651645, 0.6122987])