In [1]:
from Bio import SeqIO, Phylo
import numpy as np
import sys
sys.path.append('../pysimARG')
from fasta_to_bool import fasta_to_bool
from newick_to_tree import newick_to_tree
from clonal_genealogy import ClonalTree

In [2]:
tree = Phylo.read("../data/SimBac/clonal_frame.nwk", "newick")
Phylo.draw_ascii(tree)

                                                        _________________ 5
                                                    ___|
                                                   |   |                 , 0
                                                   |   |_________________|
           ________________________________________|                     | 10
          |                                        |
          |                                        |                    _ 11
          |                                        |___________________|
       ___|                                                            |_ 9
      |   |
      |   |                                                            __ 8
      |   |                                             ______________|
      |   |____________________________________________|              |__ 6
  ____|                                                |
 |    |                                                |_________

In [3]:
clonaltree = ClonalTree(n=15)

In [4]:
edge, node_height = newick_to_tree(tree)

In [5]:
edge

array([[1.600000e+01, 1.000000e+00, 5.464500e-03],
       [1.600000e+01, 1.100000e+01, 5.464500e-03],
       [1.700000e+01, 6.000000e+00, 1.533875e-01],
       [1.700000e+01, 1.600000e+01, 1.479230e-01],
       [1.800000e+01, 1.000000e+01, 1.867250e-02],
       [1.800000e+01, 1.200000e+01, 1.867250e-02],
       [1.900000e+01, 1.700000e+01, 3.706200e-02],
       [1.900000e+01, 1.800000e+01, 1.717770e-01],
       [2.000000e+01, 7.000000e+00, 3.300950e-02],
       [2.000000e+01, 9.000000e+00, 3.300950e-02],
       [2.100000e+01, 2.000000e+01, 1.225090e-01],
       [2.100000e+01, 3.000000e+00, 1.555185e-01],
       [2.200000e+01, 2.100000e+01, 3.736460e-01],
       [2.200000e+01, 1.900000e+01, 3.387150e-01],
       [2.300000e+01, 1.300000e+01, 9.724850e-02],
       [2.300000e+01, 4.000000e+00, 9.724850e-02],
       [2.400000e+01, 8.000000e+00, 2.207055e-01],
       [2.400000e+01, 2.300000e+01, 1.234570e-01],
       [2.500000e+01, 2.200000e+01, 3.600000e-02],
       [2.500000e+01, 2.400000e

In [6]:
node_height

array([0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.0054645, 0.1533875, 0.0186725,
       0.1904495, 0.0330095, 0.1555185, 0.5291645, 0.0972485, 0.2207055,
       0.5651645, 0.0037099, 0.0509744, 0.0690417, 0.6122987])

In [7]:
clonaltree.edge, clonaltree.node_height

(array([[1.60000000e+01, 1.00000000e+01, 1.44508209e-02],
        [1.60000000e+01, 1.20000000e+01, 1.44508209e-02],
        [1.70000000e+01, 1.00000000e+00, 3.21768652e-02],
        [1.70000000e+01, 1.40000000e+01, 3.21768652e-02],
        [1.80000000e+01, 6.00000000e+00, 5.74742197e-02],
        [1.80000000e+01, 8.00000000e+00, 5.74742197e-02],
        [1.90000000e+01, 1.80000000e+01, 1.14160654e-02],
        [1.90000000e+01, 7.00000000e+00, 6.88902851e-02],
        [2.00000000e+01, 1.90000000e+01, 1.14897493e-02],
        [2.00000000e+01, 1.70000000e+01, 4.82031691e-02],
        [2.10000000e+01, 2.00000000e+01, 6.99321638e-03],
        [2.10000000e+01, 1.30000000e+01, 8.73732507e-02],
        [2.20000000e+01, 1.10000000e+01, 1.65694193e-01],
        [2.20000000e+01, 1.60000000e+01, 1.51243372e-01],
        [2.30000000e+01, 2.00000000e+00, 1.97338081e-01],
        [2.30000000e+01, 4.00000000e+00, 1.97338081e-01],
        [2.40000000e+01, 1.50000000e+01, 2.34347695e-01],
        [2.400

In [8]:
counter = 1
for leaf in tree.get_terminals():
    if leaf.name and leaf.name.isdigit():
        leaf.node_index = int(leaf.name)
    else:
        leaf.node_index = counter
    counter += 1

terminal_indices = [leaf.node_index for leaf in tree.get_terminals()]
next_index = max(terminal_indices) + 1 if terminal_indices else 1

for clade in tree.find_clades(terminal=False, order='postorder'):
    clade.node_index = next_index
    next_index += 1

print(counter)

16


In [9]:
height_to_root = np.zeros(counter - 1)
height_to_root

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
edge

array([[1.600000e+01, 1.000000e+00, 5.464500e-03],
       [1.600000e+01, 1.100000e+01, 5.464500e-03],
       [1.700000e+01, 6.000000e+00, 1.533875e-01],
       [1.700000e+01, 1.600000e+01, 1.479230e-01],
       [1.800000e+01, 1.000000e+01, 1.867250e-02],
       [1.800000e+01, 1.200000e+01, 1.867250e-02],
       [1.900000e+01, 1.700000e+01, 3.706200e-02],
       [1.900000e+01, 1.800000e+01, 1.717770e-01],
       [2.000000e+01, 7.000000e+00, 3.300950e-02],
       [2.000000e+01, 9.000000e+00, 3.300950e-02],
       [2.100000e+01, 2.000000e+01, 1.225090e-01],
       [2.100000e+01, 3.000000e+00, 1.555185e-01],
       [2.200000e+01, 2.100000e+01, 3.736460e-01],
       [2.200000e+01, 1.900000e+01, 3.387150e-01],
       [2.300000e+01, 1.300000e+01, 9.724850e-02],
       [2.300000e+01, 4.000000e+00, 9.724850e-02],
       [2.400000e+01, 8.000000e+00, 2.207055e-01],
       [2.400000e+01, 2.300000e+01, 1.234570e-01],
       [2.500000e+01, 2.200000e+01, 3.600000e-02],
       [2.500000e+01, 2.400000e

In [11]:
for leaf in range(1, counter):
    height_to_leaf = 0
    start_node = leaf
    while start_node < (counter - 1)*2 - 1:
        mat_indices = np.where(edge[:, 1] == start_node)[0]
        parent_node = edge[mat_indices, 0][0]
        height_to_leaf += edge[mat_indices, 2][0]
        start_node = parent_node
    height_to_root[leaf - 1] = height_to_leaf

In [12]:
height_to_root

array([0.6122987, 0.6122987, 0.6122987, 0.6122987, 0.6122987, 0.6122987,
       0.6122987, 0.6122987, 0.6122987, 0.6122987, 0.6122987, 0.6122987,
       0.6122987, 0.6122987, 0.6122987])

In [37]:
min_height = np.min(height_to_root)
diff_height = height_to_root - min_height
min_height, diff_height

(np.float64(0.6122987000000001),
 array([4.7e-07, 3.0e-07, 5.0e-07, 3.0e-07, 3.0e-07, 5.0e-07, 3.0e-07,
        5.0e-07, 3.0e-07, 0.0e+00, 4.7e-07, 0.0e+00, 3.0e-07, 2.9e-07,
        2.9e-07]))

In [38]:
old_edge = edge.copy()

In [39]:
for leaf in range(1, counter):
    mat_indices = np.where(edge[:, 1] == leaf)[0]
    edge[mat_indices, 2] -= diff_height[leaf - 1]
edge

array([[2.900000e+01, 2.800000e+01, 4.713420e-02],
       [2.900000e+01, 2.100000e+01, 5.432570e-01],
       [2.800000e+01, 2.700000e+01, 3.600000e-02],
       [2.800000e+01, 2.600000e+01, 3.444590e-01],
       [2.700000e+01, 2.500000e+01, 3.387150e-01],
       [2.700000e+01, 2.400000e+01, 3.736460e-01],
       [2.500000e+01, 2.300000e+01, 3.706200e-02],
       [2.500000e+01, 1.800000e+01, 1.717770e-01],
       [2.300000e+01, 6.000000e+00, 1.533875e-01],
       [2.300000e+01, 1.700000e+01, 1.479230e-01],
       [1.700000e+01, 1.000000e+00, 5.464500e-03],
       [1.700000e+01, 1.100000e+01, 5.464500e-03],
       [1.800000e+01, 1.200000e+01, 1.867250e-02],
       [1.800000e+01, 1.000000e+01, 1.867250e-02],
       [2.400000e+01, 1.900000e+01, 1.225090e-01],
       [2.400000e+01, 3.000000e+00, 1.555185e-01],
       [1.900000e+01, 9.000000e+00, 3.300950e-02],
       [1.900000e+01, 7.000000e+00, 3.300950e-02],
       [2.600000e+01, 2.200000e+01, 1.234570e-01],
       [2.600000e+01, 8.000000e

In [16]:
old_node_height = node_height.copy()
node_height = np.full(next_index, np.nan)
node_height[:(counter-1)] = 0
old_node_height, node_height

(array([0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.0054645, 0.1533875, 0.0186725,
        0.1904495, 0.0330095, 0.1555185, 0.5291645, 0.0972485, 0.2207055,
        0.5651645, 0.0037099, 0.0509744, 0.0690417, 0.6122987]),
 array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0., nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan]))

In [17]:
for node in range(counter, (counter - 1)*2):
    mat_indices = np.where(edge[:, 0] == node)[0][1]
    leaf = edge[mat_indices, 1]
    node_height[node-1] = node_height[int(leaf)-1] + edge[mat_indices, 2]
node_height

array([0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.0054645, 0.1533875, 0.0186725,
       0.1904495, 0.0330095, 0.1555185, 0.5291645, 0.0972485, 0.2207055,
       0.5651645, 0.0037099, 0.0509744, 0.0690417, 0.6122987])

In [18]:
node_height - old_node_height

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -5.55111512e-17,  0.00000000e+00, -2.77555756e-17,  0.00000000e+00,
       -2.77555756e-17,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  5.55111512e-17, -4.16333634e-17,
        0.00000000e+00])