In [1]:
from Bio import SeqIO
import numpy as np
import sys
sys.path.append('../pysimARG')
from fasta_to_bool import fasta_to_bool

## Genome data

In [2]:
for record in SeqIO.parse("../data/SimBac/genomes.fasta", "fasta"):
    print(record.id, len(record.seq))

0 100000
1 100000
2 100000
3 100000
4 100000
5 100000
6 100000
7 100000
8 100000
9 100000


### Try and test

In [3]:
seq1 = 'TTATCAGTCTACTTTTGGCTAGCACCTCATAGAATTAAGAAGGATAGTCGCGATCAAAAGTACATAGAGTCTT'
seq2 = 'CTATCAGTCTTCTTTCGGCTAGCACCTCATAGAATTAACAAGGATGGACGCCATCAAAAGTACACACAGACTT'
seq3 = 'CTATCAGTCTACTTTCGCCTAGCACCTCATAGAATTAACAAGGATGGACGCCATCAAAAGTACACACAGAGTT'

In [4]:
list1 = list(seq1)
list2 = list(seq2)
list3 = list(seq3)

In [5]:
sequences = []
sequences.append(list1)
sequences.append(list2)
sequences.append(list3)
sequences

[['T',
  'T',
  'A',
  'T',
  'C',
  'A',
  'G',
  'T',
  'C',
  'T',
  'A',
  'C',
  'T',
  'T',
  'T',
  'T',
  'G',
  'G',
  'C',
  'T',
  'A',
  'G',
  'C',
  'A',
  'C',
  'C',
  'T',
  'C',
  'A',
  'T',
  'A',
  'G',
  'A',
  'A',
  'T',
  'T',
  'A',
  'A',
  'G',
  'A',
  'A',
  'G',
  'G',
  'A',
  'T',
  'A',
  'G',
  'T',
  'C',
  'G',
  'C',
  'G',
  'A',
  'T',
  'C',
  'A',
  'A',
  'A',
  'A',
  'G',
  'T',
  'A',
  'C',
  'A',
  'T',
  'A',
  'G',
  'A',
  'G',
  'T',
  'C',
  'T',
  'T'],
 ['C',
  'T',
  'A',
  'T',
  'C',
  'A',
  'G',
  'T',
  'C',
  'T',
  'T',
  'C',
  'T',
  'T',
  'T',
  'C',
  'G',
  'G',
  'C',
  'T',
  'A',
  'G',
  'C',
  'A',
  'C',
  'C',
  'T',
  'C',
  'A',
  'T',
  'A',
  'G',
  'A',
  'A',
  'T',
  'T',
  'A',
  'A',
  'C',
  'A',
  'A',
  'G',
  'G',
  'A',
  'T',
  'G',
  'G',
  'A',
  'C',
  'G',
  'C',
  'C',
  'A',
  'T',
  'C',
  'A',
  'A',
  'A',
  'A',
  'G',
  'T',
  'A',
  'C',
  'A',
  'C',
  'A',
  'C',
  'A',
  'G',
  'A'

In [6]:
char_matrix = np.array(sequences)
char_matrix

array([['T', 'T', 'A', 'T', 'C', 'A', 'G', 'T', 'C', 'T', 'A', 'C', 'T',
        'T', 'T', 'T', 'G', 'G', 'C', 'T', 'A', 'G', 'C', 'A', 'C', 'C',
        'T', 'C', 'A', 'T', 'A', 'G', 'A', 'A', 'T', 'T', 'A', 'A', 'G',
        'A', 'A', 'G', 'G', 'A', 'T', 'A', 'G', 'T', 'C', 'G', 'C', 'G',
        'A', 'T', 'C', 'A', 'A', 'A', 'A', 'G', 'T', 'A', 'C', 'A', 'T',
        'A', 'G', 'A', 'G', 'T', 'C', 'T', 'T'],
       ['C', 'T', 'A', 'T', 'C', 'A', 'G', 'T', 'C', 'T', 'T', 'C', 'T',
        'T', 'T', 'C', 'G', 'G', 'C', 'T', 'A', 'G', 'C', 'A', 'C', 'C',
        'T', 'C', 'A', 'T', 'A', 'G', 'A', 'A', 'T', 'T', 'A', 'A', 'C',
        'A', 'A', 'G', 'G', 'A', 'T', 'G', 'G', 'A', 'C', 'G', 'C', 'C',
        'A', 'T', 'C', 'A', 'A', 'A', 'A', 'G', 'T', 'A', 'C', 'A', 'C',
        'A', 'C', 'A', 'G', 'A', 'C', 'T', 'T'],
       ['C', 'T', 'A', 'T', 'C', 'A', 'G', 'T', 'C', 'T', 'A', 'C', 'T',
        'T', 'T', 'C', 'G', 'C', 'C', 'T', 'A', 'G', 'C', 'A', 'C', 'C',
        'T', 'C', 'A', 'T'

In [7]:
reference_seq = char_matrix[0]

bool_matrix = (char_matrix != reference_seq)
bool_matrix

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False,  True, False, False, False, False,  True, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False, False, False, False,
         True, False,  True, False, False, False,  True, Fals

### Run function

In [3]:
bool_mat = fasta_to_bool("../data/SimBac/genomes.fasta")
bool_mat.shape, bool_mat.dtype

((10, 100000), dtype('bool'))

In [4]:
np.savetxt("../data/SimBac/genomes_bool.csv", bool_mat, delimiter=",", fmt="%d")
# bool_mat = np.loadtxt("../data/SimBac/genomes_bool.csv", delimiter=",", dtype=bool)

## Tree data

In [6]:
from Bio import Phylo
from newick_to_tree import newick_to_tree
from clonal_genealogy import ClonalTree

In [3]:
tree = Phylo.read("../data/SimBac/clonal_frame.nwk", "newick")
Phylo.draw_ascii(tree)

                                                        _________________ 5
                                                    ___|
                                                   |   |                 , 0
                                                   |   |_________________|
           ________________________________________|                     | 10
          |                                        |
          |                                        |                    _ 11
          |                                        |___________________|
       ___|                                                            |_ 9
      |   |
      |   |                                                            __ 8
      |   |                                             ______________|
      |   |____________________________________________|              |__ 6
  ____|                                                |
 |    |                                                |_________

(((((5:0.153388,(0:0.00546497,10:0.00546497):0.147923):0.037062,(11:0.0186725,9:0.0186725):0.171777):0.338715,((8:0.0330098,6:0.0330098):0.122509,2:0.155519):0.373646):0.036,((12:0.0972488,3:0.0972488):0.123457,7:0.220706):0.344459):0.0471342,(4:0.069042,(1:0.0509747,(14:0.00371019,13:0.00371019):0.0472645):0.0180673):0.543257):0;

In [4]:
edge, node_height = newick_to_tree(tree)

In [5]:
edge, node_height

(array([[2.80000e+01, 2.70000e+01, 4.71342e-02],
        [2.80000e+01, 2.00000e+01, 5.43257e-01],
        [2.70000e+01, 2.60000e+01, 3.60000e-02],
        [2.70000e+01, 2.50000e+01, 3.44459e-01],
        [2.60000e+01, 2.40000e+01, 3.38715e-01],
        [2.60000e+01, 2.30000e+01, 3.73646e-01],
        [2.40000e+01, 2.20000e+01, 3.70620e-02],
        [2.40000e+01, 1.70000e+01, 1.71777e-01],
        [2.20000e+01, 5.00000e+00, 1.53388e-01],
        [2.20000e+01, 1.60000e+01, 1.47923e-01],
        [1.60000e+01, 0.00000e+00, 5.46497e-03],
        [1.60000e+01, 1.00000e+01, 5.46497e-03],
        [1.70000e+01, 1.10000e+01, 1.86725e-02],
        [1.70000e+01, 9.00000e+00, 1.86725e-02],
        [2.30000e+01, 1.80000e+01, 1.22509e-01],
        [2.30000e+01, 2.00000e+00, 1.55519e-01],
        [1.80000e+01, 8.00000e+00, 3.30098e-02],
        [1.80000e+01, 6.00000e+00, 3.30098e-02],
        [2.50000e+01, 2.10000e+01, 1.23457e-01],
        [2.50000e+01, 7.00000e+00, 2.20706e-01],
        [2.10000e+01

In [7]:
tree2 = ClonalTree(n=15)
tree2.edge

array([[1.60000000e+01, 1.10000000e+01, 2.08618762e-02],
       [1.60000000e+01, 4.00000000e+00, 2.08618762e-02],
       [1.70000000e+01, 7.00000000e+00, 2.83115717e-02],
       [1.70000000e+01, 8.00000000e+00, 2.83115717e-02],
       [1.80000000e+01, 1.00000000e+01, 3.52688587e-02],
       [1.80000000e+01, 1.20000000e+01, 3.52688587e-02],
       [1.90000000e+01, 3.00000000e+00, 3.91651901e-02],
       [1.90000000e+01, 1.00000000e+00, 3.91651901e-02],
       [2.00000000e+01, 1.30000000e+01, 9.68533954e-02],
       [2.00000000e+01, 1.70000000e+01, 6.85418238e-02],
       [2.10000000e+01, 1.40000000e+01, 1.38237338e-01],
       [2.10000000e+01, 2.00000000e+00, 1.38237338e-01],
       [2.20000000e+01, 9.00000000e+00, 1.66572763e-01],
       [2.20000000e+01, 1.80000000e+01, 1.31303904e-01],
       [2.30000000e+01, 5.00000000e+00, 2.13102593e-01],
       [2.30000000e+01, 6.00000000e+00, 2.13102593e-01],
       [2.40000000e+01, 1.90000000e+01, 2.23793749e-01],
       [2.40000000e+01, 2.00000

In [ ]:
edge[:, :2]

array([[29., 28.],
       [29., 21.],
       [28., 27.],
       [28., 26.],
       [27., 25.],
       [27., 24.],
       [25., 23.],
       [25., 18.],
       [23.,  6.],
       [23., 17.],
       [17.,  1.],
       [17., 11.],
       [18., 12.],
       [18., 10.],
       [24., 19.],
       [24.,  3.],
       [19.,  9.],
       [19.,  7.],
       [26., 22.],
       [26.,  8.],
       [22., 13.],
       [22.,  4.],
       [21.,  5.],
       [21., 20.],
       [20.,  2.],
       [20., 16.],
       [16., 15.],
       [16., 14.]])

In [9]:
tree.edge = edge
tree.node_height = node_height
tree.height = np.max(node_height)
tree.length = np.sum(edge[:, 2])

In [10]:
tree.edge, tree.node_height

(array([[2.80000e+01, 2.70000e+01, 4.71342e-02],
        [2.80000e+01, 2.00000e+01, 5.43257e-01],
        [2.70000e+01, 2.60000e+01, 3.60000e-02],
        [2.70000e+01, 2.50000e+01, 3.44459e-01],
        [2.60000e+01, 2.40000e+01, 3.38715e-01],
        [2.60000e+01, 2.30000e+01, 3.73646e-01],
        [2.40000e+01, 2.20000e+01, 3.70620e-02],
        [2.40000e+01, 1.70000e+01, 1.71777e-01],
        [2.20000e+01, 5.00000e+00, 1.53388e-01],
        [2.20000e+01, 1.60000e+01, 1.47923e-01],
        [1.60000e+01, 0.00000e+00, 5.46497e-03],
        [1.60000e+01, 1.00000e+01, 5.46497e-03],
        [1.70000e+01, 1.10000e+01, 1.86725e-02],
        [1.70000e+01, 9.00000e+00, 1.86725e-02],
        [2.30000e+01, 1.80000e+01, 1.22509e-01],
        [2.30000e+01, 2.00000e+00, 1.55519e-01],
        [1.80000e+01, 8.00000e+00, 3.30098e-02],
        [1.80000e+01, 6.00000e+00, 3.30098e-02],
        [2.50000e+01, 2.10000e+01, 1.23457e-01],
        [2.50000e+01, 7.00000e+00, 2.20706e-01],
        [2.10000e+01