In [1]:
import numpy as np

In [2]:
mat = np.array([[0, 0, 0, 1],
                [0, 1, 0, 1],
                [0, 1, 0, 1],
                [0, 1, 1, 1]])

In [10]:
n = mat.shape[0]

has_true = mat.any(axis=0)
has_false = ~mat.all(axis=0)
    
S = np.sum(has_true & has_false)

a_n = np.sum(1 / np.arange(1, n))

S, a_n

(np.int64(2), np.float64(1.8333333333333333))

In [12]:
1 / np.arange(1, n)

array([1.        , 0.5       , 0.33333333])

In [11]:
has_true, has_false, has_true & has_false

(array([False,  True,  True,  True]),
 array([ True,  True,  True, False]),
 array([False,  True,  True, False]))

In [43]:
mat = np.array([[0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1],
                [0, 0, 1, 1, 0, 0, 1, 1],
                [0, 1, 0, 1, 0, 1, 0, 1],
                [0, 0, 1, 1, 1, 1, 0, 0]])
mat

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 1, 1, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 1, 1, 0, 0]])

In [40]:
n = mat.shape[0]

pi_sum = 0
for i in range(n):
    for j in range(i + 1, n):
        pi_sum += np.sum(mat[i] != mat[j])

pi = 2 * pi_sum / (n * (n - 1))
pi_sum, pi

(np.int64(40), np.float64(4.0))

In [44]:
n = mat.shape[0]
Wakeley = True

pi_list = []
for i in range(n):
    for j in range(i + 1, n):
        pi_list.append(np.sum(mat[i] != mat[j]))

pi = 2 * np.sum(pi_list) / (n * (n - 1))
result = {'Tajima_pi': pi}

if Wakeley:
    pi2 = 2 * np.sum([(x - pi)**2 for x in pi_list]) / (n * (n - 1))
    result['Wakeley_pi2'] = pi2

result

{'Tajima_pi': np.float64(3.8), 'Wakeley_pi2': np.float64(0.36)}

In [53]:
import sys
sys.path.append('../pysimARG')
from LD_r import LD_r
from LD import LD

In [55]:
for i in range(n-1):
    for j in range(i + 1, n):
        print('------------')
        print(i, j)
        print(LD_r(mat[:, [i, j]]))
        print(LD(mat[:, [i, j]]))

------------
0 1
0.0
{'D': np.float64(0.0), 'D_prime': np.float64(0.0), 'r_square': np.float64(0.0)}
------------
0 2
0.0
{'D': np.float64(0.0), 'D_prime': np.float64(0.0), 'r_square': np.float64(0.0)}
------------
0 3
0.0
{'D': np.float64(0.0), 'D_prime': np.float64(0.0), 'r_square': np.float64(0.0)}
------------
0 4
0.0
{'D': np.float64(0.0), 'D_prime': np.float64(0.0), 'r_square': np.float64(0.0)}
------------
1 2
0.16666666666666666
{'D': np.float64(-0.08000000000000002), 'D_prime': np.float64(1.0000000000000029), 'r_square': np.float64(0.16666666666666574)}
------------
1 3
0.16666666666666674
{'D': np.float64(0.08000000000000002), 'D_prime': np.float64(0.9999999999999972), 'r_square': np.float64(0.16666666666666574)}
------------
1 4
0.0625
{'D': np.float64(-0.04000000000000001), 'D_prime': np.float64(1.0000000000000056), 'r_square': np.float64(0.062499999999999466)}
------------
2 3
0.44444444444444464
{'D': np.float64(0.16000000000000003), 'D_prime': np.float64(0.99999999999999

In [56]:
mat

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 1, 1, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 1, 1, 0, 0]])

In [57]:
has_true = mat.any(axis=0)
has_false = ~mat.all(axis=0)
idx_seg = np.where(has_true & has_false)[0]

r_squares = []
if idx_seg.size >= 2:
    for i in range(idx_seg.size - 1):
        for j in range(i + 1, idx_seg.size):
            idx_pair = [idx_seg[i], idx_seg[j]]
            r_sq = LD(mat[:, idx_pair])['r_square']
            r_squares.append(r_sq)

idx_seg, r_squares

(array([1, 2, 3, 4, 5, 6, 7]),
 [np.float64(0.16666666666666574),
  np.float64(0.16666666666666574),
  np.float64(0.062499999999999466),
  np.float64(0.16666666666666574),
  np.float64(0.16666666666666574),
  np.float64(0.16666666666666574),
  np.float64(0.4444444444444429),
  np.float64(0.3749999999999978),
  np.float64(0.027777777777777644),
  np.float64(0.027777777777777644),
  np.float64(0.027777777777777644),
  np.float64(0.16666666666666577),
  np.float64(0.02777777777777772),
  np.float64(0.027777777777777644),
  np.float64(0.02777777777777772),
  np.float64(0.16666666666666574),
  np.float64(0.16666666666666574),
  np.float64(0.3749999999999977),
  np.float64(0.027777777777777644),
  np.float64(0.02777777777777772),
  np.float64(0.4444444444444429)])

In [58]:
len(r_squares)

21

In [59]:
sum(r_squares) * 2 / (7*6)

np.float64(0.1550925925925918)

In [60]:
np.mean(r_squares)

np.float64(0.1550925925925918)

In [61]:
from Kelly_Z import Kelly_Z

In [62]:
Kelly_Z(mat)

np.float64(0.1550925925925918)

In [71]:
mat

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 1, 1, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 1, 1, 0, 0]])

In [70]:
mat.astype(bool)

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True,  True],
       [False, False,  True,  True, False, False,  True,  True],
       [False,  True, False,  True, False,  True, False,  True],
       [False, False,  True,  True,  True,  True, False, False]])

In [68]:
mat[:, 1]

array([0, 0, 0, 1, 0])

In [75]:
tuple(mat[:, 1])

(np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0))

In [76]:
mat = np.full((5, 10), np.nan)
mat

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]])

In [77]:
mat[:, 0] = np.array([0, 1, 1, 1, 1])
mat[:, 1] = np.array([0, 0, 1, 1, 1])
mat[:, 2] = np.array([0, 0, 1, 1, 1])
mat[:, 3] = np.array([1, 1, 0, 0, 0])
mat[:, 4] = np.array([0, 0, 1, 0, 1])
mat[:, 5] = np.array([1, 0, 0, 1, 0])
mat[:, 6] = np.array([0, 1, 1, 1, 1])
mat[:, 7] = np.array([0, 1, 1, 1, 1])
mat[:, 8] = np.array([0, 1, 1, 0, 0])
mat[:, 9] = np.array([1, 0, 1, 1, 1])
mat

array([[0., 0., 0., 1., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 1., 1., 1., 0.],
       [1., 1., 1., 0., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 1., 1., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 1., 0., 1.]])

In [79]:
seg_mat = mat.astype(bool)
n = seg_mat.shape[0]
S = seg_mat.shape[1]

B = 0
A = set()
for i in range(S - 1):
    if seg_mat[0, i]:
        col1 = np.logical_not(seg_mat[:, i])
    else:
        col1 = seg_mat[:, i]
    
    if seg_mat[0, i + 1]:
        col2 = np.logical_not(seg_mat[:, i + 1])
    else:
        col2 = seg_mat[:, i + 1]
    
    if np.array_equal(col1, col2):
        B += 1
        A.add(tuple(col1))

B_norm = B / (S - 1)
Q = (B + len(A)) / S
{'B': B_norm, 'Q': Q}

{'B': 0.3333333333333333, 'Q': 0.5}

In [80]:
A

{(np.False_, np.False_, np.True_, np.True_, np.True_),
 (np.False_, np.True_, np.True_, np.True_, np.True_)}

In [78]:
from Wall_BQ import Wall_BQ
Wall_BQ(mat)

{'B': 0.3333333333333333, 'Q': 0.5}