In [1]:
import numpy as np

In [2]:
mat = np.array([[0, 0, 0, 1],
                [0, 1, 0, 1],
                [0, 1, 0, 1],
                [0, 1, 1, 1]])

In [10]:
n = mat.shape[0]

has_true = mat.any(axis=0)
has_false = ~mat.all(axis=0)
    
S = np.sum(has_true & has_false)

a_n = np.sum(1 / np.arange(1, n))

S, a_n

(np.int64(2), np.float64(1.8333333333333333))

In [12]:
1 / np.arange(1, n)

array([1.        , 0.5       , 0.33333333])

In [11]:
has_true, has_false, has_true & has_false

(array([False,  True,  True,  True]),
 array([ True,  True,  True, False]),
 array([False,  True,  True, False]))

In [43]:
mat = np.array([[0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1],
                [0, 0, 1, 1, 0, 0, 1, 1],
                [0, 1, 0, 1, 0, 1, 0, 1],
                [0, 0, 1, 1, 1, 1, 0, 0]])
mat

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 1, 1, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 1, 1, 0, 0]])

In [40]:
n = mat.shape[0]

pi_sum = 0
for i in range(n):
    for j in range(i + 1, n):
        pi_sum += np.sum(mat[i] != mat[j])

pi = 2 * pi_sum / (n * (n - 1))
pi_sum, pi

(np.int64(40), np.float64(4.0))

In [44]:
n = mat.shape[0]
Wakeley = True

pi_list = []
for i in range(n):
    for j in range(i + 1, n):
        pi_list.append(np.sum(mat[i] != mat[j]))

pi = 2 * np.sum(pi_list) / (n * (n - 1))
result = {'Tajima_pi': pi}

if Wakeley:
    pi2 = 2 * np.sum([(x - pi)**2 for x in pi_list]) / (n * (n - 1))
    result['Wakeley_pi2'] = pi2

result

{'Tajima_pi': np.float64(3.8), 'Wakeley_pi2': np.float64(0.36)}

In [53]:
import sys
sys.path.append('../pysimARG')
from LD_r import LD_r
from LD import LD

In [55]:
for i in range(n-1):
    for j in range(i + 1, n):
        print('------------')
        print(i, j)
        print(LD_r(mat[:, [i, j]]))
        print(LD(mat[:, [i, j]]))

------------
0 1
0.0
{'D': np.float64(0.0), 'D_prime': np.float64(0.0), 'r_square': np.float64(0.0)}
------------
0 2
0.0
{'D': np.float64(0.0), 'D_prime': np.float64(0.0), 'r_square': np.float64(0.0)}
------------
0 3
0.0
{'D': np.float64(0.0), 'D_prime': np.float64(0.0), 'r_square': np.float64(0.0)}
------------
0 4
0.0
{'D': np.float64(0.0), 'D_prime': np.float64(0.0), 'r_square': np.float64(0.0)}
------------
1 2
0.16666666666666666
{'D': np.float64(-0.08000000000000002), 'D_prime': np.float64(1.0000000000000029), 'r_square': np.float64(0.16666666666666574)}
------------
1 3
0.16666666666666674
{'D': np.float64(0.08000000000000002), 'D_prime': np.float64(0.9999999999999972), 'r_square': np.float64(0.16666666666666574)}
------------
1 4
0.0625
{'D': np.float64(-0.04000000000000001), 'D_prime': np.float64(1.0000000000000056), 'r_square': np.float64(0.062499999999999466)}
------------
2 3
0.44444444444444464
{'D': np.float64(0.16000000000000003), 'D_prime': np.float64(0.99999999999999