In [1]:
import numpy as np

In [2]:
mat = np.array([[0, 0, 0, 1],
                [0, 1, 0, 1],
                [0, 1, 0, 1],
                [0, 1, 1, 1]])

In [10]:
n = mat.shape[0]

has_true = mat.any(axis=0)
has_false = ~mat.all(axis=0)
    
S = np.sum(has_true & has_false)

a_n = np.sum(1 / np.arange(1, n))

S, a_n

(np.int64(2), np.float64(1.8333333333333333))

In [12]:
1 / np.arange(1, n)

array([1.        , 0.5       , 0.33333333])

In [11]:
has_true, has_false, has_true & has_false

(array([False,  True,  True,  True]),
 array([ True,  True,  True, False]),
 array([False,  True,  True, False]))