In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys
sys.path.append('../../pysimARG')
from clonal_genealogy import ClonalTree
from ClonalOrigin_nodes import ClonalOrigin_nodes
from ClonalOrigin_ARG import ARG
from add_mutation import add_mutation
from G4_test import G4_test
from LD_r import LD_r
from homoplasy_index import homoplasy_index
from ClonalOrigin_seq_sim import ClonalOrigin_seq_sim

## Check inputs

In [2]:
tree1 = ClonalTree(n=15)

In [3]:
print(tree1)

ClonalTree(n=15)


In [4]:
tree1.edge

array([[1.60000000e+01, 1.00000000e+00, 1.08572187e-02],
       [1.60000000e+01, 9.00000000e+00, 1.08572187e-02],
       [1.70000000e+01, 1.60000000e+01, 1.28476567e-02],
       [1.70000000e+01, 1.20000000e+01, 2.37048754e-02],
       [1.80000000e+01, 1.30000000e+01, 2.80674227e-02],
       [1.80000000e+01, 1.70000000e+01, 4.36254739e-03],
       [1.90000000e+01, 8.00000000e+00, 8.99183764e-02],
       [1.90000000e+01, 7.00000000e+00, 8.99183764e-02],
       [2.00000000e+01, 4.00000000e+00, 1.20537762e-01],
       [2.00000000e+01, 1.90000000e+01, 3.06193861e-02],
       [2.10000000e+01, 1.80000000e+01, 1.21859336e-01],
       [2.10000000e+01, 5.00000000e+00, 1.49926759e-01],
       [2.20000000e+01, 1.40000000e+01, 1.60018807e-01],
       [2.20000000e+01, 1.50000000e+01, 1.60018807e-01],
       [2.30000000e+01, 3.00000000e+00, 1.73134239e-01],
       [2.30000000e+01, 2.00000000e+01, 5.25964767e-02],
       [2.40000000e+01, 2.00000000e+00, 1.97083976e-01],
       [2.40000000e+01, 6.00000

In [5]:
tree1.node_height

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.01085722, 0.02370488, 0.02806742, 0.08991838, 0.12053776,
       0.14992676, 0.16001881, 0.17313424, 0.19708398, 0.39782557,
       0.40876757, 0.56540963, 1.01924705, 3.9324366 ])

In [6]:
rho_site = 0.02
theta_site = 0.05
L = 2000
delta = 300

In [7]:
ARG_sim = ARG(tree1, rho_site, L, delta, L, "seq")

In [8]:
ARG_sim.edge.shape, ARG_sim.node_mat.shape

((460, 3), (353, 2000))

In [9]:
arg = ARG_sim

In [10]:
theta = theta_site * arg.node_mat.shape[1]
n_mutations = np.random.poisson(theta * arg.length / 2)

# Initialize node_site matrix (boolean)
node_site = np.zeros(
    (arg.node_mat.shape[0], arg.node_mat.shape[1]), dtype=bool
)

# If there is no mutation
if n_mutations == 0:
    print("No mutation")

# If there are mutations
# Sample edges with probability proportional to edge length
edge_probs = arg.edge[:, 2] / arg.length
mutate_edge = np.random.choice(len(arg.edge), n_mutations, replace=True, p=edge_probs)
# Sample sites uniformly (0-indexed)
mutate_site = np.random.choice(arg.node_mat.shape[1], n_mutations, replace=True)

# Ignore mutations not in the edge material
keep_mutation = []
for i in range(n_mutations):
    if arg.edge_mat[mutate_edge[i], mutate_site[i]]:
        keep_mutation.append(i)

mutate_edge = mutate_edge[keep_mutation]
mutate_site = mutate_site[keep_mutation]

if len(keep_mutation) == 0:
        print("No mutation after filtering")

In [11]:
mutate_edge, mutate_site

(array([456, 459, 419, 415, 244, 419,  38, 317, 438, 146,  38, 455, 392,
        398,  72, 245, 442, 454, 412, 456, 459,  22, 456, 225, 190, 190,
         34,  48, 277, 429, 447, 456, 456, 447, 448, 168, 447, 387, 419,
        448, 446, 456,  42, 249, 458, 459, 418, 180, 440, 415, 419, 142,
        416, 450,  61, 456,  53, 456,  60, 456, 202,  24, 120,  80, 415,
        277, 455, 447, 434, 456, 403, 438, 442, 418, 116, 240, 458, 456,
        325,  39, 442, 317, 147, 456, 438, 458, 447, 197, 458, 214, 446,
        434,   4, 446, 454,  33, 456, 450,  44,  26, 447, 334, 244, 325,
        225,  44, 459, 407, 144,  66, 405, 448, 458, 327, 446, 440, 450,
        458, 139, 317, 338, 448, 426, 454, 458,  54,  20, 387, 270, 415,
        459,  82, 202, 458, 234, 447, 458, 458, 458, 415, 442, 459, 434,
        454, 447, 332,  38,  28,  58, 415,  54, 230, 410, 458, 427, 446,
        456, 458, 459,  22, 456, 323, 456, 326, 182, 407, 446, 458, 245,
        183, 447, 322, 144,  40, 453, 181, 395, 458

In [12]:
mutate_edge.shape, mutate_site.shape

((497,), (497,))

In [14]:
for i in range(len(arg.edge) - 1, -1, -1):
    print(f"Processing edge {i}")

Processing edge 459
Processing edge 458
Processing edge 457
Processing edge 456
Processing edge 455
Processing edge 454
Processing edge 453
Processing edge 452
Processing edge 451
Processing edge 450
Processing edge 449
Processing edge 448
Processing edge 447
Processing edge 446
Processing edge 445
Processing edge 444
Processing edge 443
Processing edge 442
Processing edge 441
Processing edge 440
Processing edge 439
Processing edge 438
Processing edge 437
Processing edge 436
Processing edge 435
Processing edge 434
Processing edge 433
Processing edge 432
Processing edge 431
Processing edge 430
Processing edge 429
Processing edge 428
Processing edge 427
Processing edge 426
Processing edge 425
Processing edge 424
Processing edge 423
Processing edge 422
Processing edge 421
Processing edge 420
Processing edge 419
Processing edge 418
Processing edge 417
Processing edge 416
Processing edge 415
Processing edge 414
Processing edge 413
Processing edge 412
Processing edge 411
Processing edge 410


In [17]:
mutate_site[mutate_edge == 459]

array([1518, 1450, 1423, 1492, 1472, 1508, 1455, 1587, 1444, 1566, 1499,
       1473, 1475, 1503, 1491, 1440, 1517, 1559, 1465, 1525, 1511, 1445,
       1293, 1410, 1579, 1294], dtype=int32)

In [20]:
root_node = np.random.choice([True, False], size=2000)
root_node

array([ True,  True,  True, ...,  True,  True, False], shape=(2000,))

In [23]:
arg.node_mat.shape[0]

353

In [24]:
node_site.shape

(353, 2000)

In [21]:
np.tile(root_node, (10, 1))

array([[ True,  True,  True, ...,  True,  True, False],
       [ True,  True,  True, ...,  True,  True, False],
       [ True,  True,  True, ...,  True,  True, False],
       ...,
       [ True,  True,  True, ...,  True,  True, False],
       [ True,  True,  True, ...,  True,  True, False],
       [ True,  True,  True, ...,  True,  True, False]], shape=(10, 2000))

In [8]:
s_vec = ClonalOrigin_seq_sim(tree1, rho_site, theta_site, L, delta)
s_vec

array([6.79922636e-03, 5.05842755e-03, 8.52519186e-03, 1.13746254e-02,
       7.11297071e-02, 2.22000000e-01, 2.00000000e+03])