In [1]:
import numpy as np
import sys
sys.path.append('../../pysimARG')
from add_mutation import add_mutation

In [73]:
mutate_edge = np.array([86, 24, 12, 71, 17, 35, 86, 68, 86, 67]) - 1
mutate_site = np.array([2, 1, 2, 2, 1, 1, 1, 2, 2, 1]) - 1
print(mutate_edge)
print(mutate_site)

[85 23 11 70 16 34 85 67 85 66]
[1 0 1 1 0 0 0 1 1 0]


In [74]:
n_mutations = 10
edge_mat = np.array([
    [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 0], [0, 1], [1, 0], [1, 1],
    [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [0, 1], [1, 1], [1, 1], [1, 0], [0, 1],
    [1, 0], [0, 1], [1, 0], [0, 1], [0, 0], [1, 0], [0, 0], [0, 0], [1, 0], [0, 1],
    [1, 0], [1, 0], [1, 1], [1, 0], [0, 0], [0, 0], [1, 1], [0, 1], [0, 0], [0, 1],
    [1, 1], [0, 0], [0, 1], [0, 0], [1, 1], [0, 0], [0, 0], [0, 1], [0, 0], [0, 1],
    [1, 0], [0, 1], [1, 0], [0, 1], [1, 0], [0, 1], [1, 0], [0, 0], [0, 1], [0, 0],
    [1, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0],
    [0, 0], [0, 1], [0, 0], [0, 0], [0, 1], [0, 1], [0, 0], [1, 0], [0, 1], [0, 0],
    [0, 1], [1, 0], [1, 1], [0, 0], [1, 1], [0, 0]
])
edge = np.array([
    [11,     7, 0.0205380361],
    [11,     6, 0.0205380361],
    [12,     9, 0.1065758788],
    [12,    10, 0.1065758788],
    [13,    11, 0.0929780739],
    [13,     8, 0.1135161100],
    [14,    13, 0.0958692194],
    [15,    13, 0.0958692194],
    [16,    14, 0.0004732405],
    [16,     3, 0.2098585698],
    [17,     2, 0.2379657492],
    [17,    12, 0.1313898704],
    [18,     5, 0.3753210475],
    [18,    17, 0.1373552983],
    [19,    18, 0.0260884199],
    [19,    15, 0.1920241380],
    [20,     4, 0.4074049540],
    [20,    16, 0.1975463841],
    [21,    20, 0.0866376796],
    [22,    20, 0.0866376796],
    [23,    19, 0.1130066453],
    [24,    19, 0.1130066453],
    [25,     1, 0.5219369723],
    [26,     1, 0.5219369723],
    [27,    25, 0.0276397893],
    [28,    25, 0.0276397893],
    [29,    27, 0.0480855813],
    [30,    27, 0.0480855813],
    [31,    23, 0.1628124462],
    [32,    22, 0.1831859254],
    [33,    21, 0.2351942819],
    [34,    28, 0.1796601539],
    [35,    31, 0.0928147642],
    [36,    32, 0.0408064077],
    [37,    29, 0.3324048253],
    [38,    29, 0.3324048253],
    [36,    33, 0.1794087530],
    [36,    24, 0.4350359634],
    [37,    34, 0.0221257899],
    [37,    26, 0.4302559858],
    [38,    36, 0.0699144183],
    [38,    30, 0.4217041516],
    [39,    37, 0.2057032768],
    [40,    37, 0.2057032768],
    [41,    38, 0.3714460578],
    [41,    35, 0.4607453840],
    [42,    39, 0.2342707552],
    [43,    39, 0.2342707552],
    [44,    42, 0.0725647670],
    [44,    43, 0.0725647670],
    [45,    41, 0.1049452897],
    [46,    41, 0.1049452897],
    [47,    45, 0.0131013756],
    [47,    46, 0.0131013756],
    [48,    47, 0.1257516557],
    [49,    47, 0.1257516557],
    [50,    48, 0.0309186482],
    [50,    40, 0.5076332865],
    [51,    44, 0.2174696896],
    [52,    44, 0.2174696896],
    [53,    50, 0.1199962817],
    [53,    52, 0.1033243565],
    [54,    53, 0.2220233659],
    [55,    53, 0.2220233659],
    [56,    54, 0.0467645207],
    [57,    54, 0.0467645207],
    [58,    51, 0.4153258237],
    [59,    51, 0.4153258237],
    [60,    56, 0.0443991569],
    [61,    56, 0.0443991569],
    [62,    60, 0.2153181544],
    [62,    59, 0.2165037306],
    [63,    58, 0.2847589005],
    [64,    58, 0.2847589005],
    [65,    62, 0.0864440035],
    [65,    49, 0.7658641312],
    [66,    63, 0.0438247398],
    [66,    55, 0.4185617416],
    [67,    65, 0.1558640128],
    [67,    57, 0.5020253276],
    [68,    67, 0.0432566285],
    [68,    66, 0.1734847352],
    [69,    68, 0.2334352476],
    [69,    64, 0.4507447225],
    [70,    69, 1.3084051539],
    [70,    61, 2.0427232007]
])

In [75]:
node_site = np.zeros(
        (70, 2), dtype=bool
    )

In [76]:
# Ignore mutations not in the edge material
keep_mutation = []
for i in range(n_mutations):
    if edge_mat[mutate_edge[i], mutate_site[i]]:
        keep_mutation.append(i)

mutate_edge = mutate_edge[keep_mutation]
mutate_site = mutate_site[keep_mutation]

In [77]:
print(keep_mutation)
print(mutate_edge)
print(mutate_site)

[2, 4, 7]
[11 16 67]
[1 0 1]


In [78]:
# Simulate the mutations at every node
# Process edges from last to first (bottom-up in the tree)
for i in range(len(edge) - 1, -1, -1):
    # Get mutations on this edge (sites that have mutations on edge i)
    edge_mutation = mutate_site[mutate_edge == i]

    parent_idx = int(edge[i, 0]) - 1
    child_idx = int(edge[i, 1]) - 1

    # Get parent sequence
    parent_seq = node_site[parent_idx, :].copy()

    # Count mutations at each site (equivalent to R's tabulate)
    flip_counts = np.bincount(edge_mutation, minlength=len(parent_seq))

    # XOR with whether flip count is odd
    parent_seq = np.logical_xor(parent_seq, flip_counts % 2 == 1)

    # Get material range for this edge
    material_range = edge_mat[i, :]

    # Update child node sequence only where there's material
    node_site[child_idx, material_range==True] = parent_seq[material_range==True]

In [49]:
print(node_site[24, :])

[False False]


In [60]:
i = 22
edge_mutation = mutate_site[mutate_edge == i+1]

parent_idx = int(edge[i, 0]) - 1
child_idx = int(edge[i, 1]) - 1

# Get parent sequence
parent_seq = node_site[parent_idx, :].copy()

# Count mutations at each site (equivalent to R's tabulate)
flip_counts = np.bincount(edge_mutation, minlength=len(parent_seq))

# XOR with whether flip count is odd
parent_seq = np.logical_xor(parent_seq, flip_counts % 2 == 1)

# Get material range for this edge
material_range = edge_mat[i, :]

# Update child node sequence only where there's material
node_site[child_idx, material_range==True] = parent_seq[material_range==True]

In [61]:
edge_mutation

array([], dtype=int64)

In [62]:
material_range

array([1, 0])

In [63]:
parent_seq[material_range==True]

array([False])

In [64]:
node_site[child_idx, material_range==True]

array([False])

In [35]:
mutate_edge

array([12, 17, 68])

In [79]:
test_node_site = np.array([
    [0, 1], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 1],
    [0, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],
    [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0],
    [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 1], [0, 0],
    [0, 0], [0, 0], [0, 1], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],
    [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],
    [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]
])

In [80]:
test_node_site == node_site

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ Tr