In [1]:
import numpy as np
from scipy.stats import poisson
import sys
sys.path.append('../../pysimARG')
from add_mutation_truncated import truncated_poisson
from clonal_genealogy import ClonalTree
from ClonalOrigin_pair import ARG

In [2]:
np.random.seed(100)
tree = ClonalTree(10)

rho_site = 0.5
theta_site = 0.3
L = 100
delta = 5
k = 10

In [3]:
ARG = ARG(tree, rho_site, L, delta, k)

In [4]:
ARG.edge

array([[1.10000000e+01, 1.00000000e+01, 1.74212971e-02],
       [1.10000000e+01, 7.00000000e+00, 1.74212971e-02],
       [1.20000000e+01, 9.00000000e+00, 1.84379429e-02],
       [1.30000000e+01, 9.00000000e+00, 1.84379429e-02],
       [1.40000000e+01, 1.20000000e+01, 5.53498546e-03],
       [1.40000000e+01, 1.10000000e+01, 6.55163127e-03],
       [1.50000000e+01, 8.00000000e+00, 3.12932844e-02],
       [1.50000000e+01, 1.40000000e+01, 7.32035608e-03],
       [1.60000000e+01, 1.50000000e+01, 8.98432793e-03],
       [1.60000000e+01, 3.00000000e+00, 4.02776123e-02],
       [1.70000000e+01, 6.00000000e+00, 6.64131035e-02],
       [1.80000000e+01, 6.00000000e+00, 6.64131035e-02],
       [1.90000000e+01, 1.70000000e+01, 1.17395840e-03],
       [1.90000000e+01, 1.60000000e+01, 2.73094496e-02],
       [2.00000000e+01, 1.90000000e+01, 3.24496679e-02],
       [2.10000000e+01, 1.90000000e+01, 3.24496679e-02],
       [2.20000000e+01, 4.00000000e+00, 1.16275318e-01],
       [2.30000000e+01, 4.00000

In [5]:
ARG.edge_mat

array([[1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.]])

In [6]:
ARG.node_mat.shape[1]

2

In [9]:
np.where(ARG.edge_mat[:, 0])[0]

array([ 0,  1,  3,  5,  6,  7,  8,  9, 10, 12, 13, 14, 17, 18, 19, 20, 21,
       24, 28, 29, 31, 32, 34, 36, 37, 38, 40, 41, 42, 44])

In [7]:
np.where(ARG.edge_mat[:, 0] == 1)

(array([ 0,  1,  3,  5,  6,  7,  8,  9, 10, 12, 13, 14, 17, 18, 19, 20, 21,
        24, 28, 29, 31, 32, 34, 36, 37, 38, 40, 41, 42, 44]),)

In [11]:
l_1 = list()
l_1.extend([0] * 5)
l_1

[0, 0, 0, 0, 0]

In [12]:
num_site = ARG.node_mat.shape[1]
n_list = np.zeros(num_site, dtype=int)
mutate_edge = list()
mutate_site = list()

# Initialize node_site matrix (boolean)
node_site = np.zeros(
    (ARG.node_mat.shape[0], ARG.node_mat.shape[1]), dtype=bool
)

In [13]:
i = 0

In [14]:
# Length of local tree without reduction
local_edge = np.where(ARG.edge_mat[:, i])[0]
local_length = ARG.edge[local_edge, 2]
# Truncated Poisson distribution
local_n = truncated_poisson(theta_site * np.sum(local_length) / 2)
n_list[i] = local_n
mutate_site.extend([i] * local_n)

In [20]:
probs = local_length / np.sum(local_length)
np.random.choice(local_edge, 3, replace=True, p=probs)

array([44, 44, 32])

In [24]:
mutate_edge.extend(np.random.choice(local_edge, 3, replace=True, p=probs).tolist())

In [25]:
mutate_edge

[np.int64(34), np.int64(28), np.int64(17), 29, 31, 17]

In [26]:
np.random.choice(5, 10, replace=True)

array([3, 0, 1, 1, 3, 0, 4, 2, 4, 3], dtype=int32)

In [38]:
arg_1_length = np.sum(ARG.edge[ARG.edge_mat[:, 0] == 1, 2])
arg_1_length

np.float64(3.112456887852887)

In [39]:
import scipy.stats as stats

stats.expon.logcdf(arg_1_length, scale=1/(theta_site/2))

np.float64(-0.9860763543710639)