In [1]:
import numpy as np
import scipy.stats as stats
import sys
sys.path.append('../../pysimARG')
from clonal_genealogy import ClonalTree
from ClonalOrigin_nodes import ClonalOrigin_nodes
from ClonalOrigin_pair import ARG

In [2]:
np.random.seed(0)
tree = ClonalTree(n=15)
rho_site = 0.2
L = 100000
delta = 5000
k = 2000
theta_site = 0.2
theta = theta_site * 2

In [3]:
np.random.seed(1)
ARG_1 = ARG(tree, rho_site, L, delta, k)

In [36]:
arg_list = [None] * 100
log_weight_list = [None] * 100
weight_list = [None] * 100
for i in range(100):
    print(i)
    np.random.seed(i)
    ARG_i = ARG(tree, rho_site, L, delta, k)
    arg_list[i] = ARG_i
    log_weight_list[i] = stats.expon.logcdf(ARG_i.length, scale=1/(theta/2))
    weight_list[i] = 1 - np.exp(-theta * ARG_i.length / 2)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [41]:
log_weight_list

[np.float64(-2.750686051290026e-143),
 np.float64(-5.591718172910593e-141),
 np.float64(-1.4044145425331539e-143),
 np.float64(-1.4040969135896348e-145),
 np.float64(-8.36183910195795e-146),
 np.float64(-1.3897295656931602e-139),
 np.float64(-7.737292742711614e-146),
 np.float64(-9.858575378791689e-138),
 np.float64(-4.181055222320534e-139),
 np.float64(-9.09627981932166e-142),
 np.float64(-3.9930299645236893e-146),
 np.float64(-1.3105192870419269e-140),
 np.float64(-3.3052780966236624e-139),
 np.float64(-3.908797276563647e-145),
 np.float64(-2.5147133399343425e-147),
 np.float64(-1.898626267044469e-144),
 np.float64(-4.939290231170018e-143),
 np.float64(-7.154625335244084e-140),
 np.float64(-4.790948468610752e-137),
 np.float64(-1.8962766283832207e-133),
 np.float64(-2.7065128559736926e-145),
 np.float64(-9.608048385258624e-135),
 np.float64(-3.990238364363368e-138),
 np.float64(-2.713966402403364e-142),
 np.float64(-1.4398641468458283e-143),
 np.float64(-1.1603806880814137e-149),
 np

In [49]:
log_weight_list = np.array(log_weight_list)

In [50]:
log_weight_list

array([-2.75068605e-143, -5.59171817e-141, -1.40441454e-143,
       -1.40409691e-145, -8.36183910e-146, -1.38972957e-139,
       -7.73729274e-146, -9.85857538e-138, -4.18105522e-139,
       -9.09627982e-142, -3.99302996e-146, -1.31051929e-140,
       -3.30527810e-139, -3.90879728e-145, -2.51471334e-147,
       -1.89862627e-144, -4.93929023e-143, -7.15462534e-140,
       -4.79094847e-137, -1.89627663e-133, -2.70651286e-145,
       -9.60804839e-135, -3.99023836e-138, -2.71396640e-142,
       -1.43986415e-143, -1.16038069e-149, -8.28196479e-148,
       -8.78592315e-144, -1.50375742e-145, -6.97863201e-144,
       -6.16704176e-147, -3.66717287e-141, -6.72184990e-148,
       -3.91857736e-140, -5.48548682e-137, -7.08284930e-143,
       -2.44561412e-145, -4.97854987e-151, -5.95848163e-144,
       -1.24980875e-146, -1.43176500e-144, -1.57526099e-135,
       -5.88152847e-142, -2.13554176e-148, -4.77059187e-147,
       -5.34194382e-139, -4.45817643e-145, -5.26206594e-141,
       -2.64578201e-143,

In [53]:
x = np.array(range(100))
log_p = log_weight_list
n = len(x)

# 1. Subtract the max for numerical stability (Log-Sum-Exp trick)
shifted_log_p = log_p - np.max(log_p)

# 2. Exponentiate to get raw weights
weights = np.exp(shifted_log_p)

# 3. Normalize the weights so they sum to exactly 1.0
probs = weights / np.sum(weights)

# 4. Sample with replacement
# Equivalent to R: sample(x, size=n, replace=TRUE, prob=probs)
sampled_values = np.random.choice(x, size=n, replace=True, p=probs)

print(sampled_values)
print(probs)

[36 26  6 99 53 88 32 20 11  9 55 17  4  2 42  6 18 74 49  7 66 92 72 86
  8 64 71 74 54 91 80 73 71 51 68  3 94 49 54 15 97  9  1 92 41 99 33 65
 72 34 25 98 19 68 94 97 89 35 69  4 95 27 21 38 20 10 42  2 54 12 39 99
 25 62 33 66 66 65 29 92 41 19 31 59 47 38 43 24 27  2  2 47 47 97 93 50
 30 64 23 76]
[0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01]


In [54]:
shifted_log_p

array([-2.75068604e-143, -5.59171817e-141, -1.40441453e-143,
       -1.40409575e-145, -8.36182751e-146, -1.38972957e-139,
       -7.73728115e-146, -9.85857538e-138, -4.18105522e-139,
       -9.09627982e-142, -3.99301837e-146, -1.31051929e-140,
       -3.30527810e-139, -3.90879612e-145, -2.51459741e-147,
       -1.89862615e-144, -4.93929022e-143, -7.15462534e-140,
       -4.79094847e-137, -1.89627663e-133, -2.70651170e-145,
       -9.60804839e-135, -3.99023836e-138, -2.71396640e-142,
       -1.43986414e-143, -1.14878783e-149, -8.28080550e-148,
       -8.78592303e-144, -1.50375626e-145, -6.97863189e-144,
       -6.16692583e-147, -3.66717287e-141, -6.72069062e-148,
       -3.91857736e-140, -5.48548682e-137, -7.08284929e-143,
       -2.44561296e-145, -3.81926418e-151, -5.95848151e-144,
       -1.24979716e-146, -1.43176489e-144, -1.57526099e-135,
       -5.88152847e-142, -2.13438247e-148, -4.77047594e-147,
       -5.34194382e-139, -4.45817527e-145, -5.26206594e-141,
       -2.64578200e-143,

In [34]:
log_p

[np.float64(-2.750686051290026e-143),
 np.float64(-5.591718172910593e-141),
 np.float64(-1.4044145425331539e-143),
 np.float64(-1.4040969135896348e-145),
 np.float64(-8.36183910195795e-146),
 np.float64(-1.3897295656931602e-139),
 np.float64(-7.737292742711614e-146),
 np.float64(-9.858575378791689e-138),
 np.float64(-4.181055222320534e-139),
 np.float64(-9.09627981932166e-142),
 np.float64(-3.9930299645236893e-146),
 np.float64(-1.3105192870419269e-140),
 np.float64(-3.3052780966236624e-139),
 np.float64(-3.908797276563647e-145),
 np.float64(-2.5147133399343425e-147),
 np.float64(-1.898626267044469e-144),
 np.float64(-4.939290231170018e-143),
 np.float64(-7.154625335244084e-140),
 np.float64(-4.790948468610752e-137),
 np.float64(-1.8962766283832207e-133),
 np.float64(-2.7065128559736926e-145),
 np.float64(-9.608048385258624e-135),
 np.float64(-3.990238364363368e-138),
 np.float64(-2.713966402403364e-142),
 np.float64(-1.4398641468458283e-143),
 np.float64(-1.1603806880814137e-149),
 np

In [43]:
arg_list[i].edge_mat

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       ...,
       [0., 0.],
       [1., 1.],
       [0., 0.]], shape=(15736, 2))

In [33]:
x = np.array(range(100))
log_p = log_weight_list
n = len(x)

# 2. Exponentiate to get raw weights
weights = np.exp(log_p)

# 3. Normalize the weights so they sum to exactly 1.0
probs = weights / np.sum(weights)

# 4. Sample with replacement
# Equivalent to R: sample(x, size=n, replace=TRUE, prob=probs)
sampled_values = np.random.choice(x, size=n, replace=True, p=probs)

print(sampled_values)
print(probs)

[22 75  3  8  3  1 94 36 26  6 99 53 88 32 20 11  9 55 17  4  2 42  6 18
 74 49  7 66 92 72 86  8 64 71 74 54 91 80 73 71 51 68  3 94 49 54 15 97
  9  1 92 41 99 33 65 72 34 25 98 19 68 94 97 89 35 69  4 95 27 21 38 20
 10 42  2 54 12 39 99 25 62 33 66 66 65 29 92 41 19 31 59 47 38 43 24 27
  2  2 47 47]
[0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01]


In [44]:
from scipy.stats import poisson


def truncated_poisson(lam, size=1):
    """
    Samples from a Zero-Truncated Poisson distribution.
    """
    p0 = np.exp(-lam)

    eps = np.finfo(float).eps
    u = np.random.uniform(low=eps+p0, high=1.0, size=size)

    return poisson.ppf(u, lam).astype(int)

In [4]:
from ClonalOrigin_simulator import ClonalOrigin_simulator


ClonalOrigin_simulator(tree, rho_site, theta_site, L, delta, 100,
                       k_vec=[50, 200, 2000])

array([0.08476654, 0.05425856, 0.06006227, 0.41      , 0.43      ,
       0.48      , 0.98      ])