In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys
sys.path.append('../../pysimARG')
from clonal_genealogy import ClonalTree
from ClonalOrigin_nodes import ClonalOrigin_nodes
from ClonalOrigin_ARG import ARG
from add_mutation import add_mutation
from G3_test import G3_test
from LD_r import LD_r
from homoplasy_index import homoplasy_index
from ClonalOrigin_seq_sim import ClonalOrigin_seq_sim

## Check inputs

In [2]:
tree1 = ClonalTree(n=15)

In [3]:
print(tree1)

ClonalTree(n=15)


In [4]:
tree1.edge

array([[1.60000000e+01, 1.20000000e+01, 1.91916009e-02],
       [1.60000000e+01, 4.00000000e+00, 1.91916009e-02],
       [1.70000000e+01, 3.00000000e+00, 2.58772275e-02],
       [1.70000000e+01, 8.00000000e+00, 2.58772275e-02],
       [1.80000000e+01, 1.10000000e+01, 2.79362129e-02],
       [1.80000000e+01, 6.00000000e+00, 2.79362129e-02],
       [1.90000000e+01, 1.40000000e+01, 4.09485952e-02],
       [1.90000000e+01, 1.60000000e+01, 2.17569943e-02],
       [2.00000000e+01, 1.30000000e+01, 5.57284233e-02],
       [2.00000000e+01, 1.70000000e+01, 2.98511958e-02],
       [2.10000000e+01, 1.80000000e+01, 3.92180208e-02],
       [2.10000000e+01, 9.00000000e+00, 6.71542336e-02],
       [2.20000000e+01, 1.00000000e+01, 7.49438761e-02],
       [2.20000000e+01, 1.50000000e+01, 7.49438761e-02],
       [2.30000000e+01, 2.10000000e+01, 5.98217013e-02],
       [2.30000000e+01, 2.00000000e+00, 1.26975935e-01],
       [2.40000000e+01, 2.30000000e+01, 2.84674546e-02],
       [2.40000000e+01, 5.00000

In [5]:
tree1.node_height

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.0191916 , 0.02587723, 0.02793621, 0.0409486 , 0.05572842,
       0.06715423, 0.07494388, 0.12697593, 0.15544339, 0.20534186,
       0.30883214, 0.65873004, 1.15692469, 1.4260558 ])

## Seq function with long chain

In [7]:
L = 1000000

In [8]:
rho_site = 0.02
delta = 300

In [9]:
ARG_1 = ARG(tree1, rho_site, L, delta, L, "seq")
ARG_1.edge

MemoryError: Unable to allocate 1.27 TiB for an array with shape (174236, 1000000) and data type float64

Even setting the matrix data type to bool, it still requires:

In [12]:
print(174236 * 1000000 / 1000000000.0, "(Gb)")

174.236 (Gb)


## Try and test simulator

In [13]:
rho_site = 0.02
theta_site = 0.05
L = 2000
delta = 300

In [14]:
ARG_sim = ARG(tree1, rho_site, L, delta, L, "seq")

In [15]:
ARG_sim.edge.shape, ARG_sim.node_mat.shape

((608, 3), (464, 2000))

In [17]:
node_site = add_mutation(ARG_sim, theta_site)
node_site.shape

(464, 2000)

In [20]:
node_site

array([[False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False,  True],
       [False,  True, False, ..., False, False,  True],
       ...,
       [False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False, False]], shape=(464, 2000))

In [25]:
mat = node_site[:15, :]
mat

array([[False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False,  True],
       [False,  True, False, ..., False, False,  True],
       ...,
       [False,  True, False, ..., False, False,  True],
       [False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False,  True]], shape=(15, 2000))

In [35]:
s = 0
s_idx = []
for i in range(2000):
    s_false = np.sum(mat[:, i] == False)
    s_true = np.sum(mat[:, i] == True)
    if s_false > 0 and s_true > 0:
        s += 1
        s_idx.append(i)
s, s_idx

(347,
 [1,
  5,
  7,
  8,
  9,
  12,
  13,
  19,
  21,
  25,
  30,
  31,
  39,
  45,
  50,
  63,
  68,
  94,
  96,
  98,
  101,
  109,
  124,
  137,
  140,
  147,
  157,
  174,
  207,
  214,
  215,
  223,
  225,
  232,
  236,
  238,
  249,
  251,
  255,
  258,
  259,
  272,
  282,
  294,
  296,
  299,
  306,
  307,
  309,
  311,
  317,
  322,
  329,
  342,
  343,
  348,
  349,
  353,
  355,
  356,
  359,
  362,
  364,
  366,
  372,
  377,
  385,
  387,
  393,
  395,
  402,
  410,
  417,
  420,
  427,
  428,
  435,
  442,
  444,
  445,
  455,
  456,
  460,
  463,
  466,
  470,
  471,
  474,
  482,
  493,
  497,
  506,
  513,
  518,
  521,
  524,
  540,
  544,
  548,
  549,
  561,
  588,
  598,
  605,
  606,
  607,
  612,
  616,
  626,
  632,
  633,
  634,
  638,
  647,
  649,
  651,
  661,
  668,
  671,
  684,
  688,
  691,
  695,
  696,
  704,
  721,
  724,
  731,
  739,
  766,
  772,
  775,
  777,
  778,
  781,
  782,
  791,
  792,
  793,
  794,
  795,
  803,
  804,
  809,
  816,
  81

In [ ]:
has_true = mat.any(axis=0)
has_false = ~mat.all(axis=0)
count_S = (has_true & has_false).sum()
count_S

np.int64(347)

In [46]:
has_seg = has_true & has_false
has_seg.sum()

np.int64(347)

In [45]:
np.sum(np.where(has_seg)[0] == np.array(s_idx))

np.int64(347)

In [50]:
idx_seg = np.where(has_seg)[0]
idx_seg

array([   1,    5,    7,    8,    9,   12,   13,   19,   21,   25,   30,
         31,   39,   45,   50,   63,   68,   94,   96,   98,  101,  109,
        124,  137,  140,  147,  157,  174,  207,  214,  215,  223,  225,
        232,  236,  238,  249,  251,  255,  258,  259,  272,  282,  294,
        296,  299,  306,  307,  309,  311,  317,  322,  329,  342,  343,
        348,  349,  353,  355,  356,  359,  362,  364,  366,  372,  377,
        385,  387,  393,  395,  402,  410,  417,  420,  427,  428,  435,
        442,  444,  445,  455,  456,  460,  463,  466,  470,  471,  474,
        482,  493,  497,  506,  513,  518,  521,  524,  540,  544,  548,
        549,  561,  588,  598,  605,  606,  607,  612,  616,  626,  632,
        633,  634,  638,  647,  649,  651,  661,  668,  671,  684,  688,
        691,  695,  696,  704,  721,  724,  731,  739,  766,  772,  775,
        777,  778,  781,  782,  791,  792,  793,  794,  795,  803,  804,
        809,  816,  819,  825,  827,  835,  853,  8

In [63]:
s = 0
for i in range(idx_seg[:10].size - 1):
    for j in range(i + 1, idx_seg[:10].size):
        print(i, j)
        dist_ij = idx_seg[j] - idx_seg[i]
        print(dist_ij)
        s += 1
s

0 1
4
0 2
6
0 3
7
0 4
8
0 5
11
0 6
12
0 7
18
0 8
20
0 9
24
1 2
2
1 3
3
1 4
4
1 5
7
1 6
8
1 7
14
1 8
16
1 9
20
2 3
1
2 4
2
2 5
5
2 6
6
2 7
12
2 8
14
2 9
18
3 4
1
3 5
4
3 6
5
3 7
11
3 8
13
3 9
17
4 5
3
4 6
4
4 7
10
4 8
12
4 9
16
5 6
1
5 7
7
5 8
9
5 9
13
6 7
6
6 8
8
6 9
12
7 8
2
7 9
6
8 9
4


45

In [71]:
ld_near, ld_far, g3_near, g3_far = 0, 0, 0, 0
if idx_seg.size >= 2:
    for i in range(idx_seg.size - 1):
        for j in range(i + 1, idx_seg.size):
            dist_ij = idx_seg[j] - idx_seg[i]
            idx_pair = [idx_seg[i], idx_seg[j]]
            if dist_ij < L/2:
                ld_near += LD_r(mat[:, idx_pair])
                g3_near += G3_test(mat[:, idx_pair])
            else:
                ld_far += LD_r(mat[:, idx_pair])
                g3_far += G3_test(mat[:, idx_pair])
    print([ld_near, ld_far, g3_near, g3_far])
else:
    print(0)

[np.float64(6520.988748621214), np.float64(1757.5587616414957), 8322, 4087]


In [73]:
ld_near, ld_far, g3_near, g3_far = 0, 0, 0, 0
for i in range(2000-1):
    for j in range(i + 1, 2000):
        dist_ij = j - i
        idx_pair = [i, j]
        if dist_ij < L/2:
            ld_near += LD_r(mat[:, idx_pair])
            g3_near += G3_test(mat[:, idx_pair])
        else:
            ld_far += LD_r(mat[:, idx_pair])
            g3_far += G3_test(mat[:, idx_pair])
print([ld_near, ld_far, g3_near, g3_far])

[np.float64(6520.988748621214), np.float64(1757.5587616414957), 8322, 4087]


In [ ]:
[2, 3, 4, 5] / [1, 2, 1, 2])

TypeError: unsupported operand type(s) for /: 'list' and 'list'