In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys
sys.path.append('../../pysimARG')
from clonal_genealogy import ClonalTree
from ClonalOrigin_nodes import ClonalOrigin_nodes
from ClonalOrigin_ARG import ARG
from add_mutation import add_mutation
from G3_test import G3_test
from LD_r import LD_r
from homoplasy_index import homoplasy_index
from ClonalOrigin_seq_sim import ClonalOrigin_seq_sim

## Check inputs

In [2]:
tree1 = ClonalTree(n=15)

In [3]:
print(tree1)

ClonalTree(n=15)


In [4]:
tree1.edge

array([[1.60000000e+01, 1.20000000e+01, 1.91916009e-02],
       [1.60000000e+01, 4.00000000e+00, 1.91916009e-02],
       [1.70000000e+01, 3.00000000e+00, 2.58772275e-02],
       [1.70000000e+01, 8.00000000e+00, 2.58772275e-02],
       [1.80000000e+01, 1.10000000e+01, 2.79362129e-02],
       [1.80000000e+01, 6.00000000e+00, 2.79362129e-02],
       [1.90000000e+01, 1.40000000e+01, 4.09485952e-02],
       [1.90000000e+01, 1.60000000e+01, 2.17569943e-02],
       [2.00000000e+01, 1.30000000e+01, 5.57284233e-02],
       [2.00000000e+01, 1.70000000e+01, 2.98511958e-02],
       [2.10000000e+01, 1.80000000e+01, 3.92180208e-02],
       [2.10000000e+01, 9.00000000e+00, 6.71542336e-02],
       [2.20000000e+01, 1.00000000e+01, 7.49438761e-02],
       [2.20000000e+01, 1.50000000e+01, 7.49438761e-02],
       [2.30000000e+01, 2.10000000e+01, 5.98217013e-02],
       [2.30000000e+01, 2.00000000e+00, 1.26975935e-01],
       [2.40000000e+01, 2.30000000e+01, 2.84674546e-02],
       [2.40000000e+01, 5.00000

In [5]:
tree1.node_height

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.0191916 , 0.02587723, 0.02793621, 0.0409486 , 0.05572842,
       0.06715423, 0.07494388, 0.12697593, 0.15544339, 0.20534186,
       0.30883214, 0.65873004, 1.15692469, 1.4260558 ])

## Seq function with long chain

In [7]:
L = 1000000

In [8]:
rho_site = 0.02
delta = 300

In [9]:
ARG_1 = ARG(tree1, rho_site, L, delta, L, "seq")
ARG_1.edge

MemoryError: Unable to allocate 1.27 TiB for an array with shape (174236, 1000000) and data type float64

Even setting the matrix data type to bool, it still requires:

In [12]:
print(174236 * 1000000 / 1000000000.0, "(Gb)")

174.236 (Gb)


## Try and test simulator

In [13]:
rho_site = 0.02
theta_site = 0.05
L = 2000
delta = 300

In [14]:
ARG_sim = ARG(tree1, rho_site, L, delta, L, "seq")

In [15]:
ARG_sim.edge.shape, ARG_sim.node_mat.shape

((608, 3), (464, 2000))

In [17]:
node_site = add_mutation(ARG_sim, theta_site)
node_site.shape

(464, 2000)

In [20]:
node_site

array([[False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False,  True],
       [False,  True, False, ..., False, False,  True],
       ...,
       [False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False, False]], shape=(464, 2000))

In [25]:
mat = node_site[:15, :]
mat

array([[False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False,  True],
       [False,  True, False, ..., False, False,  True],
       ...,
       [False,  True, False, ..., False, False,  True],
       [False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False,  True]], shape=(15, 2000))

In [ ]:
s = 0
for i in range(2000):
    s_false = np.sum(mat[:, i] == False)
    s_true = np.sum(mat[:, i] == True)
    if s_false > 0 and s_true > 0:
        s += 1
s

347

In [34]:
has_true = mat.any(axis=0)
has_false = ~mat.all(axis=0)
count_S = (has_true & has_false).sum()
count_S

np.int64(347)