In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys
sys.path.append('../../pysimARG')
from clonal_genealogy import ClonalTree
from ClonalOrigin_nodes import ClonalOrigin_nodes
from ClonalOrigin_ARG import ARG
from add_mutation import add_mutation
from G3_test import G3_test
from LD_r import LD_r
from homoplasy_index import homoplasy_index
from ClonalOrigin_seq_sim import ClonalOrigin_seq_sim

## Check inputs

In [2]:
tree1 = ClonalTree(n=15)

In [3]:
print(tree1)

ClonalTree(n=15)


In [4]:
tree1.edge

array([[1.60000000e+01, 1.50000000e+01, 1.51294921e-02],
       [1.60000000e+01, 1.40000000e+01, 1.51294921e-02],
       [1.70000000e+01, 1.20000000e+01, 1.85031711e-02],
       [1.70000000e+01, 4.00000000e+00, 1.85031711e-02],
       [1.80000000e+01, 1.30000000e+01, 2.30492956e-02],
       [1.80000000e+01, 1.00000000e+00, 2.30492956e-02],
       [1.90000000e+01, 1.80000000e+01, 2.50104040e-02],
       [1.90000000e+01, 2.00000000e+00, 4.80596996e-02],
       [2.00000000e+01, 6.00000000e+00, 7.50964901e-02],
       [2.00000000e+01, 1.00000000e+01, 7.50964901e-02],
       [2.10000000e+01, 9.00000000e+00, 1.02150671e-01],
       [2.10000000e+01, 1.90000000e+01, 5.40909718e-02],
       [2.20000000e+01, 5.00000000e+00, 1.03719681e-01],
       [2.20000000e+01, 7.00000000e+00, 1.03719681e-01],
       [2.30000000e+01, 2.20000000e+01, 4.33258621e-02],
       [2.30000000e+01, 1.70000000e+01, 1.28542372e-01],
       [2.40000000e+01, 1.60000000e+01, 1.59604306e-01],
       [2.40000000e+01, 3.00000

In [5]:
tree1.node_height

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.01512949, 0.01850317, 0.0230493 , 0.0480597 , 0.07509649,
       0.10215067, 0.10371968, 0.14704554, 0.1747338 , 0.18007446,
       0.46675034, 0.47241229, 0.48126175, 2.13022658])

## Seq function with long chain

In [7]:
L = 1000000

In [8]:
rho_site = 0.02
delta = 300

In [9]:
ARG_1 = ARG(tree1, rho_site, L, delta, L, "seq")
ARG_1.edge

MemoryError: Unable to allocate 1.27 TiB for an array with shape (174236, 1000000) and data type float64

Even setting the matrix data type to bool, it still requires:

In [12]:
print(174236 * 1000000 / 1000000000.0, "(Gb)")

174.236 (Gb)


## Try and test simulator

In [6]:
rho_site = 0.02
theta_site = 0.05
L = 2000
delta = 300

In [7]:
ARG_sim = ARG(tree1, rho_site, L, delta, L, "seq")

In [8]:
ARG_sim.edge.shape, ARG_sim.node_mat.shape

((652, 3), (497, 2000))

In [9]:
node_site = add_mutation(ARG_sim, theta_site)
node_site.shape

(497, 2000)

In [10]:
s_vec = ClonalOrigin_seq_sim(tree1, rho_site, theta_site, L, delta)
s_vec

array([7.44392373e-03, 4.78615734e-03, 6.38571905e-03, 1.02277722e-02,
       3.47394541e-02, 1.94500000e-01, 2.00000000e+03])