In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng()

In [3]:
rng

Generator(PCG64) at 0x2554CDADA80

In [6]:
probstart = np.ones(100, dtype=float)
probstart

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
probstart[0] = float(15)
probstart /= probstart.sum()
probstartcum = np.cumsum(probstart)

In [8]:
probstart

array([0.13157895, 0.00877193, 0.00877193, 0.00877193, 0.00877193,
       0.00877193, 0.00877193, 0.00877193, 0.00877193, 0.00877193,
       0.00877193, 0.00877193, 0.00877193, 0.00877193, 0.00877193,
       0.00877193, 0.00877193, 0.00877193, 0.00877193, 0.00877193,
       0.00877193, 0.00877193, 0.00877193, 0.00877193, 0.00877193,
       0.00877193, 0.00877193, 0.00877193, 0.00877193, 0.00877193,
       0.00877193, 0.00877193, 0.00877193, 0.00877193, 0.00877193,
       0.00877193, 0.00877193, 0.00877193, 0.00877193, 0.00877193,
       0.00877193, 0.00877193, 0.00877193, 0.00877193, 0.00877193,
       0.00877193, 0.00877193, 0.00877193, 0.00877193, 0.00877193,
       0.00877193, 0.00877193, 0.00877193, 0.00877193, 0.00877193,
       0.00877193, 0.00877193, 0.00877193, 0.00877193, 0.00877193,
       0.00877193, 0.00877193, 0.00877193, 0.00877193, 0.00877193,
       0.00877193, 0.00877193, 0.00877193, 0.00877193, 0.00877193,
       0.00877193, 0.00877193, 0.00877193, 0.00877193, 0.00877

In [9]:
probstartcum

array([0.13157895, 0.14035088, 0.14912281, 0.15789474, 0.16666667,
       0.1754386 , 0.18421053, 0.19298246, 0.20175439, 0.21052632,
       0.21929825, 0.22807018, 0.23684211, 0.24561404, 0.25438596,
       0.26315789, 0.27192982, 0.28070175, 0.28947368, 0.29824561,
       0.30701754, 0.31578947, 0.3245614 , 0.33333333, 0.34210526,
       0.35087719, 0.35964912, 0.36842105, 0.37719298, 0.38596491,
       0.39473684, 0.40350877, 0.4122807 , 0.42105263, 0.42982456,
       0.43859649, 0.44736842, 0.45614035, 0.46491228, 0.47368421,
       0.48245614, 0.49122807, 0.5       , 0.50877193, 0.51754386,
       0.52631579, 0.53508772, 0.54385965, 0.55263158, 0.56140351,
       0.57017544, 0.57894737, 0.5877193 , 0.59649123, 0.60526316,
       0.61403509, 0.62280702, 0.63157895, 0.64035088, 0.64912281,
       0.65789474, 0.66666667, 0.6754386 , 0.68421053, 0.69298246,
       0.70175439, 0.71052632, 0.71929825, 0.72807018, 0.73684211,
       0.74561404, 0.75438596, 0.76315789, 0.77192982, 0.78070

In [10]:
pool = list(range(1, 10 + 1))
pool

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [12]:
np.array(pool, dtype=int) - 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
pool = np.array(list(range(1, 10 + 1)), dtype=int)
pool

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np.array(range(1, 10 + 1), dtype=int) - 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.random.exponential(scale=1.0)

0.02298957660442996

In [18]:
a = np.random.exponential(scale=1.0)
a

1.34916189982826

In [19]:
float(a)

1.34916189982826

In [23]:
leaf = np.random.choice(pool, size=2, replace=False)
leaf

array([3, 6])

In [24]:
leaf - 1

array([2, 5])

In [25]:
pool[leaf - 1]

array([3, 6])

In [26]:
np.array([0, 0, 1, 1]) | np.array([0, 1, 0, 1])

array([0, 1, 1, 1])

In [2]:
s = np.array([], dtype=int)

In [3]:
s.size

0

In [4]:
np.random.binomial(1 * s.size, (1 - 1 / 5))

0

In [5]:
np.random.binomial(1 * 10, (1 - 1 / 5))

9

In [7]:
remain_index = np.random.choice(np.arange(10), 0, replace=False)
remain_index

array([], dtype=int64)

In [12]:
remain_index = np.random.choice(np.array([10]), 1, replace=False)
remain_index

array([10])

In [13]:
len(s)

0