In [1]:
import numpy as np

In [ ]:
mat = np.array([[0, 0, 0, 1],
                [0, 1, 0, 1],
                [0, 1, 0, 1],
                [0, 1, 1, 1]])

In [ ]:
n = mat.shape[0]

has_true = mat.any(axis=0)
has_false = ~mat.all(axis=0)
    
S = np.sum(has_true & has_false)

a_n = np.sum(1 / np.arange(1, n))

S, a_n

In [ ]:
1 / np.arange(1, n)

In [ ]:
has_true, has_false, has_true & has_false

In [ ]:
mat = np.array([[0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1],
                [0, 0, 1, 1, 0, 0, 1, 1],
                [0, 1, 0, 1, 0, 1, 0, 1],
                [0, 0, 1, 1, 1, 1, 0, 0]])
mat

In [ ]:
n = mat.shape[0]

pi_sum = 0
for i in range(n):
    for j in range(i + 1, n):
        pi_sum += np.sum(mat[i] != mat[j])

pi = 2 * pi_sum / (n * (n - 1))
pi_sum, pi

In [ ]:
n = mat.shape[0]
Wakeley = True

pi_list = []
for i in range(n):
    for j in range(i + 1, n):
        pi_list.append(np.sum(mat[i] != mat[j]))

pi = 2 * np.sum(pi_list) / (n * (n - 1))
result = {'Tajima_pi': pi}

if Wakeley:
    pi2 = 2 * np.sum([(x - pi)**2 for x in pi_list]) / (n * (n - 1))
    result['Wakeley_pi2'] = pi2

result

In [3]:
import sys
sys.path.append('../../pysimARG')
from LD_r import LD_r
from LD import LD

In [ ]:
for i in range(n-1):
    for j in range(i + 1, n):
        print('------------')
        print(i, j)
        print(LD_r(mat[:, [i, j]]))
        print(LD(mat[:, [i, j]]))

In [ ]:
mat

In [ ]:
has_true = mat.any(axis=0)
has_false = ~mat.all(axis=0)
idx_seg = np.where(has_true & has_false)[0]

r_squares = []
if idx_seg.size >= 2:
    for i in range(idx_seg.size - 1):
        for j in range(i + 1, idx_seg.size):
            idx_pair = [idx_seg[i], idx_seg[j]]
            r_sq = LD(mat[:, idx_pair])['r_square']
            r_squares.append(r_sq)

idx_seg, r_squares

In [ ]:
len(r_squares)

In [ ]:
sum(r_squares) * 2 / (7*6)

In [ ]:
np.mean(r_squares)

In [ ]:
from Kelly_Z import Kelly_Z

In [ ]:
Kelly_Z(mat)

In [ ]:
mat

In [ ]:
mat.astype(bool)

In [ ]:
mat[:, 1]

In [ ]:
tuple(mat[:, 1])

In [ ]:
mat = np.full((5, 10), np.nan)
mat

In [ ]:
mat[:, 0] = np.array([0, 1, 1, 1, 1])
mat[:, 1] = np.array([0, 0, 1, 1, 1])
mat[:, 2] = np.array([0, 0, 1, 1, 1])
mat[:, 3] = np.array([1, 1, 0, 0, 0])
mat[:, 4] = np.array([0, 0, 1, 0, 1])
mat[:, 5] = np.array([1, 0, 0, 1, 0])
mat[:, 6] = np.array([0, 1, 1, 1, 1])
mat[:, 7] = np.array([0, 1, 1, 1, 1])
mat[:, 8] = np.array([0, 1, 1, 0, 0])
mat[:, 9] = np.array([1, 0, 1, 1, 1])
mat

In [ ]:
seg_mat = mat.astype(bool)
n = seg_mat.shape[0]
S = seg_mat.shape[1]

B = 0
A = set()
for i in range(S - 1):
    if seg_mat[0, i]:
        col1 = np.logical_not(seg_mat[:, i])
    else:
        col1 = seg_mat[:, i]
    
    if seg_mat[0, i + 1]:
        col2 = np.logical_not(seg_mat[:, i + 1])
    else:
        col2 = seg_mat[:, i + 1]
    
    if np.array_equal(col1, col2):
        B += 1
        A.add(tuple(col1))

B_norm = B / (S - 1)
Q = (B + len(A)) / S
{'B': B_norm, 'Q': Q}

In [ ]:
A

In [ ]:
from Wall_BQ import Wall_BQ
Wall_BQ(mat)

In [ ]:
from G4_test import G4_test

In [ ]:
mat = np.array([
        [0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 1],
        [1, 0, 0, 1, 0, 0],
        [1, 0, 1, 1, 0, 1]
    ])
mat

In [ ]:
n_sites = mat.shape[1]
    
incompatible_intervals = []

for i in range(n_sites - 1):
    for j in range(i + 1, n_sites):
        
        if G4_test(mat[:, [i, j]]):
            incompatible_intervals.append((i, j))

if not incompatible_intervals:
    print(0)

incompatible_intervals.sort(key=lambda x: x[1])

rm_count = 0
last_cut = -1

for start, end in incompatible_intervals:
    if start > last_cut:
        last_cut = end - 1
        rm_count += 1

In [ ]:
incompatible_intervals, rm_count

In [ ]:
incompatible_intervals = [(0, 2), (0, 4), (3, 7), (5, 7), (7, 9)]

In [ ]:
incompatible_intervals.sort(key=lambda x: x[1])

rm_count = 0
last_cut = -1

for start, end in incompatible_intervals:
    if start > last_cut:
        last_cut = end - 1
        rm_count += 1
incompatible_intervals, rm_count

In [4]:
from clonal_genealogy import ClonalTree
from newick_to_tree import newick_to_tree
from ClonalOrigin_seq_sim import ClonalOrigin_seq_sim
from Bio import Phylo

In [5]:
genome_simbac = np.loadtxt("../../data/SimBac/genomes_bool.csv", delimiter=",", dtype=bool)

In [6]:
genome_simbac.shape

(30, 1000000)

In [7]:
np.random.seed(100)
clonal_tree = ClonalTree(n=30)

# Load phylo tree and convert to ClonalTree format
phylo_tree = Phylo.read("../../data/SimBac/clonal_frame.nwk", "newick")
Phylo.draw_ascii(phylo_tree)

edge, node_height = newick_to_tree(phylo_tree)
clonal_tree.edge = edge
clonal_tree.node_height = node_height
clonal_tree.height = np.max(node_height)
clonal_tree.length = np.sum(edge[:, 2])

                                                                    ____ 14
                                                                   |
                                                                   |    , 15
                                                        ___________|   _|
                                                       |           |  | , 5
                                                       |           |  | |
                                                       |           |__| | 24
                                                       |              |
                                                       |              | , 27
                                                       |              |_|
                                                       |                | 4
                                                       |
                                                       |      __________ 18
                                             

In [9]:
edge, node_height

(array([[3.1000000e+01, 6.0000000e+00, 6.1213600e-03],
        [3.1000000e+01, 2.5000000e+01, 6.1213600e-03],
        [3.2000000e+01, 1.6000000e+01, 7.8007000e-03],
        [3.2000000e+01, 3.1000000e+01, 1.6793400e-03],
        [3.3000000e+01, 5.0000000e+00, 8.0777000e-03],
        [3.3000000e+01, 2.8000000e+01, 8.0777000e-03],
        [3.4000000e+01, 3.2000000e+01, 4.8099700e-02],
        [3.4000000e+01, 3.3000000e+01, 4.7822700e-02],
        [3.5000000e+01, 3.4000000e+01, 7.9141300e-02],
        [3.5000000e+01, 1.5000000e+01, 1.3504170e-01],
        [3.6000000e+01, 2.7000000e+01, 4.0198094e-02],
        [3.6000000e+01, 1.3000000e+01, 4.0198094e-02],
        [3.7000000e+01, 1.2000000e+01, 4.0501100e-02],
        [3.7000000e+01, 3.6000000e+01, 3.0300600e-04],
        [3.8000000e+01, 9.0000000e+00, 1.4197200e-02],
        [3.8000000e+01, 1.0000000e+00, 1.4197200e-02],
        [3.9000000e+01, 2.6000000e+01, 4.9888500e-02],
        [3.9000000e+01, 3.8000000e+01, 3.5691300e-02],
        [4

In [12]:
np.savetxt("../../data/SimBac/clonal_edge.csv", edge, delimiter=",")
np.savetxt("../../data/SimBac/clonal_node_height.csv", node_height, delimiter=",")

In [16]:
clonal_edge = np.loadtxt("../../data/SimBac/clonal_edge.csv", delimiter=",", dtype=float)
clonal_node_height = np.loadtxt("../../data/SimBac/clonal_node_height.csv", delimiter=",", dtype=float)

In [17]:
clonal_edge == edge

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ T

In [18]:
clonal_node_height == node_height

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [7]:
from ClonalOrigin_ARG import ARG
from add_mutation import add_mutation

In [8]:
ARG_sim = ARG(clonal_tree, 0.02, 5000, 300, 5000, "seq")
node_site = add_mutation(ARG_sim, 0.05)
node_site.shape

(1064, 5000)

In [ ]:
node_site

In [ ]:
clonal_tree.edge

In [ ]:
partition1 = np.array([0, 0, 1, 1])
partition2 = np.array([1, 1, 1, 1])

len1 = len(np.unique(partition1))
len2 = len(np.unique(partition2))

len1, len2

In [ ]:
mat = node_site[:10, :]
mat.shape

In [ ]:
has_true = mat.any(axis=0)
has_false = ~mat.all(axis=0)
idx_seg = np.where(has_true & has_false)[0]

r_squares = []
distances = []
if idx_seg.size >= 2:
    for i in range(idx_seg.size - 1):
        for j in range(i + 1, idx_seg.size):
            dist_ij = idx_seg[j] - idx_seg[i]
            idx_pair = [idx_seg[i], idx_seg[j]]
            r_sq = LD(mat[:, idx_pair])['r_square']
            r_squares.append(r_sq)
            distances.append(dist_ij)

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
df = pd.DataFrame({'x': distances, 'y': r_squares})

# Group by 'x' and calculate the mean of 'y'
mean_y = df.groupby('x')['y'].mean().reset_index()

print(mean_y)

In [ ]:
plt.scatter(list(mean_y['x']), list(mean_y['y']))

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit


def shifted_exponential(x, a, b, c):
    """
    a: Amplitude
    b: Growth/decay rate
    c: Vertical shift (asymptote)
    """
    return a * np.exp(-b * x) + c

# np.random.seed(42)
# x_data = np.linspace(0, 4, 50)
# y_true = shifted_exponential(x_data, 2.5, 1.2, 5.0)
# y_data = y_true + 2.0 * np.random.normal(size=x_data.size)
x_data = np.array(mean_y['x'])
x_scaled = x_data - np.min(x_data)
y_data = np.array(mean_y['y'])

initial_guess = [1.0, 1.0, np.min(y_data)] 

popt, pcov = curve_fit(shifted_exponential, x_scaled, y_data, p0=initial_guess)

a_opt, b_opt, c_opt = popt
print(f"Fitted parameters:")
print(f"a = {a_opt:.3f}")
print(f"b = {b_opt:.3f}")
print(f"c = {c_opt:.3f} (Vertical shift)")

plt.figure(figsize=(8, 5))
plt.scatter(x_data, y_data, label='Noisy Data', color='gray', alpha=0.7)

x_fit = np.linspace(min(x_scaled), max(x_scaled), 100)
plt.plot(x_fit, shifted_exponential(x_fit, *popt), label='Fitted Exponential', color='red', linewidth=2)

plt.xlabel('X')
plt.ylabel('Y')
plt.title('Shifted Exponential Regression')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

In [ ]:
popt

In [ ]:
tuple(popt)

In [ ]:
array1 = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
array1[1:4] = tuple(popt)
array1

In [9]:
from ClonalOrigin_seq_sim import ClonalOrigin_seq_sim

np.random.seed(100)
s_vec = ClonalOrigin_seq_sim(clonal_tree, 0.02, 0.05, 6000, 300)
s_vec

array([-8.72000000e+00,  5.94777778e+00,  5.94787705e+05,  1.62984726e+05,
        6.00112401e+04,  1.27084376e+04,  1.15646000e+05,  4.52600000e+04,
       -1.30876104e-05,  3.11212969e-05,  8.92700663e-01,  8.52805238e-01,
        9.00692354e-02,  6.64959375e-02,  1.73569931e-01,  2.36819523e-01,
        5.30111111e+00, -4.96444444e+00,  8.88672183e+03,  8.76567368e+03,
        2.19298853e+03,  1.85411970e+03,  5.55000000e+02,  8.69000000e+02,
        5.78092815e-04, -5.39965678e-04,  9.69108160e-01,  9.53412408e-01,
        2.39148150e-01,  2.01666271e-01,  6.05234460e-02,  9.45181640e-02,
        4.89278752e-01,  2.18333333e-01,  3.30669985e+02,  2.90781609e+02,
        1.55988741e+04, -4.72045390e-01,  1.91749427e-01,  2.46564885e-01,
        1.39000000e+02,  8.48146743e-02,  2.05177578e-01,  5.55904805e-03,
        7.11224008e-02,  6.00000000e+03])

In [10]:
import pandas as pd
from ClonalOrigin_ARG import ARG
from add_mutation import add_mutation
from G4_test import G4_test
from LD import LD
from homoplasy_index import homoplasy_index
from Watterson_theta import Watterson_theta
from Tajima_pi import Tajima_pi
from Tajima_D import Tajima_D
from Wall_BQ import Wall_BQ
from Hudson_Rm import Hudson_Rm
from exp_regression import exp_regression
import warnings
warnings.filterwarnings('ignore', category=RuntimeWarning)


def ClonalOrigin_seq_sim(tree, rho_site, theta_site, L, delta):
    """
    Simulate approximated ARG using ClonalOrigin with sequential method.
    
    Simulate pairs of sites in the ClonalOrigin approximation from a given clonal tree.
    Provide summary statistics for pairs in three different distances.
    
    Parameters
    ----------
    tree : ClonalTree
        The clonal genealogy.
    rho_site : float
        The recombination parameter per site.
    theta_site : float
        The mutation rate per site.
    L : int
        The number of sites.
    delta : float
        The mean of recombinant segment length.
    
    Returns
    -------
    np.ndarray
        A 46-dimensional vector as the summary statistics of simulations.
    """
    if not isinstance(L, int):
        raise ValueError("`L` must be a single integer!")

    s_vec = np.full(46, np.nan).astype(float)
    tree_width = tree.n

    ARG_sim = ARG(tree, rho_site, L, delta, L, "seq")
    node_site = add_mutation(ARG_sim, theta_site)
    mat = node_site[:tree_width, :]

    # Identify segregating sites
    has_true = mat.any(axis=0)
    has_false = ~mat.all(axis=0)
    idx_seg = np.where(has_true & has_false)[0]

    # Summary statistics LD r and G4 test
    seg_near, seg_far = 0, 0
    seg_20_50, seg_50_80 = 0, 0
    D_near, D_far, D_prime_near, D_prime_far, r2_near, r2_far = 0, 0, 0, 0, 0, 0
    g4_near, g4_far = 0, 0
    D_20_50, D_50_80, D_prime_20_50, D_prime_50_80, r2_20_50, r2_50_80 = 0, 0, 0, 0, 0, 0
    g4_20_50, g4_50_80 = 0, 0
    r_squares = []
    distances = []
    if idx_seg.size >= 2:
        for i in range(idx_seg.size - 1):
            for j in range(i + 1, idx_seg.size):
                dist_ij = idx_seg[j] - idx_seg[i]
                idx_pair = [idx_seg[i], idx_seg[j]]

                LD_result = LD(mat[:, idx_pair])
                r_sq = LD_result['r_square']
                r_squares.append(r_sq)
                distances.append(dist_ij)

                if dist_ij < L/2:
                    D_near += LD_result['D']
                    D_prime_near += LD_result['D_prime']
                    r2_near += LD_result['r_square']
                    g4_near += G4_test(mat[:, idx_pair])
                    seg_near += 1
                else:
                    D_far += LD_result['D']
                    D_prime_far += LD_result['D_prime']
                    r2_far += LD_result['r_square']
                    g4_far += G4_test(mat[:, idx_pair])
                    seg_far += 1
                if 20 <= dist_ij < 50:
                    D_20_50 += LD_result['D']
                    D_prime_20_50 += LD_result['D_prime']
                    r2_20_50 += LD_result['r_square']
                    g4_20_50 += G4_test(mat[:, idx_pair])
                    seg_20_50 += 1
                if 50 <= dist_ij <= 80:
                    D_50_80 += LD_result['D']
                    D_prime_50_80 += LD_result['D_prime']
                    r2_50_80 += LD_result['r_square']
                    g4_50_80 += G4_test(mat[:, idx_pair])
                    seg_50_80 += 1
        
        s_vec[0] = D_near
        s_vec[1] = D_far
        s_vec[2] = D_prime_near
        s_vec[3] = D_prime_far
        s_vec[4] = r2_near
        s_vec[5] = r2_far

        s_vec[6] = g4_near
        s_vec[7] = g4_far

        s_vec[8] = D_near / seg_near if seg_near > 0 else 0
        s_vec[9] = D_far / seg_far if seg_far > 0 else 0
        s_vec[10] = D_prime_near / seg_near if seg_near > 0 else 0
        s_vec[11] = D_prime_far / seg_far if seg_far > 0 else 0
        s_vec[12] = r2_near / seg_near if seg_near > 0 else 0
        s_vec[13] = r2_far / seg_far if seg_far > 0 else 0

        s_vec[14] = g4_near / seg_near if seg_near > 0 else 0
        s_vec[15] = g4_far / seg_far if seg_far > 0 else 0

        s_vec[16] = D_20_50
        s_vec[17] = D_50_80
        s_vec[18] = D_prime_20_50
        s_vec[19] = D_prime_50_80
        s_vec[20] = r2_20_50
        s_vec[21] = r2_50_80

        s_vec[22] = g4_20_50
        s_vec[23] = g4_50_80

        s_vec[24] = D_20_50 / seg_20_50 if seg_20_50 > 0 else 0
        s_vec[25] = D_50_80 / seg_50_80 if seg_50_80 > 0 else 0
        s_vec[26] = D_prime_20_50 / seg_20_50 if seg_20_50 > 0 else 0
        s_vec[27] = D_prime_50_80 / seg_50_80 if seg_50_80 > 0 else 0
        s_vec[28] = r2_20_50 / seg_20_50 if seg_20_50 > 0 else 0
        s_vec[29] = r2_50_80 / seg_50_80 if seg_50_80 > 0 else 0

        s_vec[30] = g4_20_50 / seg_20_50 if seg_20_50 > 0 else 0
        s_vec[31] = g4_50_80 / seg_50_80 if seg_50_80 > 0 else 0
    else:
        s_vec[:32] = 0
        s_vec[42] = 0 # Kelly's Zns estimator
    
    # Summary statistic homoplasy index
    s_vec[32] = homoplasy_index(tree, node_site)

    # Summary statistic clade homoplasy index
    # s_vec[33] = clade_homoplasy(tree, node_site)

    # Summary statistic proportion of segregating sites
    count_S = idx_seg.size
    s_vec[33] = count_S / L

    # Watterson's theta estimator
    s_vec[34] = Watterson_theta(mat, count_S)

    # Tajima's pi estimators
    tajima_dict = Tajima_pi(mat, Wakeley=True)
    s_vec[35] = tajima_dict['pi']
    s_vec[36] = tajima_dict['pi2']

    # Tajima's D statistic
    s_vec[37] = Tajima_D(mat, s_vec[35], s_vec[34], count_S)

    # Wall's B and Q statistics
    wall_dict = Wall_BQ(mat[:, idx_seg])
    s_vec[38] = wall_dict['B']
    s_vec[39] = wall_dict['Q']

    # Hudson's Rm estimator
    s_vec[40] = Hudson_Rm(mat)

    # Kelly's Zns estimator
    s_vec[41] = np.mean(r_squares)

    # Regression coefficient of r^2 on distance
    if len(r_squares) >= 2:
        df = pd.DataFrame({'x': distances, 'y': r_squares})
        mean_df = df.groupby('x')['y'].mean().reset_index()
        try:
            coeff = exp_regression(np.array(mean_df['x']), np.array(mean_df['y']))
            s_vec[42:45] = coeff
        except RuntimeError as e:
            s_vec[42:45] = 0
    else:
        s_vec[42:45] = 0

    # Add the length of sequence as a summary statistic
    s_vec[45] = L
    
    return s_vec

In [11]:
np.random.seed(100)
s_vec = ClonalOrigin_seq_sim(clonal_tree, 0.02, 0.05, 6000, 300)
s_vec

array([-8.72000000e+00,  5.94777778e+00,  5.94787705e+05,  1.62984726e+05,
        6.00112401e+04,  1.27084376e+04,  1.15646000e+05,  4.52600000e+04,
       -1.30876104e-05,  3.11212969e-05,  8.92700663e-01,  8.52805238e-01,
        9.00692354e-02,  6.64959375e-02,  1.73569931e-01,  2.36819523e-01,
        5.30111111e+00, -4.96444444e+00,  8.88672183e+03,  8.76567368e+03,
        2.19298853e+03,  1.85411970e+03,  5.55000000e+02,  8.69000000e+02,
        5.78092815e-04, -5.39965678e-04,  9.69108160e-01,  9.53412408e-01,
        2.39148150e-01,  2.01666271e-01,  6.05234460e-02,  9.45181640e-02,
        4.89278752e-01,  2.18333333e-01,  3.30669985e+02,  2.90781609e+02,
        1.55988741e+04, -4.72045390e-01,  1.91749427e-01,  2.46564885e-01,
        1.39000000e+02,  8.48146743e-02,  2.05177578e-01,  5.55904805e-03,
        7.11224008e-02,  6.00000000e+03])

In [ ]:
np.array([-8.72000000e+00,  5.94777778e+00,  5.94787705e+05,  1.62984726e+05,
           6.00112401e+04,  1.27084376e+04,  1.15646000e+05,  4.52600000e+04,
          -1.30876104e-05,  3.11212969e-05,  8.92700663e-01,  8.52805238e-01,
           9.00692354e-02,  6.64959375e-02,  1.73569931e-01,  2.36819523e-01,
           5.30111111e+00, -4.96444444e+00,  8.88672183e+03,  8.76567368e+03,
           2.19298853e+03,  1.85411970e+03,  5.55000000e+02,  8.69000000e+02,
           5.78092815e-04, -5.39965678e-04,  9.69108160e-01,  9.53412408e-01,
           2.39148150e-01,  2.01666271e-01,  6.05234460e-02,  9.45181640e-02,
           4.89278752e-01,  2.18333333e-01,  3.30669985e+02,  2.90781609e+02,
           1.55988741e+04, -4.72045390e-01,  1.91749427e-01,  2.46564885e-01,
           1.39000000e+02,  8.48146743e-02,  2.05177578e-01,  5.55904805e-03,
           7.11224008e-02,  6.00000000e+03])